### ISSUE TITLE
Links in the News feed should open in a new window

### ISSUE THREAD

**Issue by DennisRas** [Adam13531/BotLand#10]
**Steps to reproduce**
- Play the game
- Login
- Click a link in the news feed

**Expected outcome**
- Opening the link in a new window/tab

**Actual outcome**
- Redirects you causing you to leave the game and having to login again

**Bowser information**
{"name":"Chrome","chrome":true,"version":"55.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 18
Player name: Liquidor

**Comment by Adam13531** [comment]
Fixed, thanks for reporting!
