### ISSUE TITLE
Wrong error message when attempting to prettify erroneous JavaScript code

### ISSUE THREAD

**Issue by Adam13531** [Adam13531/BotLand#100]
**Steps to reproduce**
1. Open JavaScript editor
2. Type any bad code, e.g. "{{{{{{"
3. Press the "Prettify" button

**Expected outcome**
An error message saying something about how you can't prettify erroneous code and to fix the errors first.

**Actual outcome**
An error message about this: "Prettifying your code would push it above the maximum character limit. Delete some code and try again."

**Browser (and version)**
Doesn't matter

**Operating system (and version)**
Doesn't matter

**Comment by Skedog** [comment]
This is no longer an issue as the "prettify" button for JS no longer exists in Bot Land, so closing for now. When I asked @Adam13531 regarding this, he says the button may come back in the future, in which case this may still apply, but for now it is irrelevant.
