### ISSUE TITLE
Sliders too far down in Firefox in new settings dialog

### ISSUE THREAD

**Issue by freaktechnik** [Adam13531/BotLand#102]
**Steps to reproduce**
 - Open Firefox
 - Got to play.bot.land
 - Log in
 - Open settings dialog

**Expected outcome**
 - Volume sliders are on the same height as the master volume slider. Resp. their container with `display: table` is where their parent is positioned.

**Actual outcome**
It's below:
![screen shot 2017-10-21 at 22 54 25](https://user-images.githubusercontent.com/640949/31855831-605605aa-b6b3-11e7-964e-3c1b74d26f87.png)

**Bowser information**
{"name":"Firefox","firefox":true,"version":"58.0a1","gecko":true,"linux":true,"a":true}

**In-game information**
Player ID: 1731
Player name: freaktechnik

**Suggested fix**
Remove the `display: flex; justify-content: center;` from the parent, since those aren't useful when the child has `height: 100%; width: 100%;` either way. Though this does also seem like a bug with Firefox, not sure really.

**Comment by freaktechnik** [comment]
I've filed a bug against Firefox for this, since this seems like wrong behavior by Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1410670

**Comment by Adam13531** [comment]
Commit hash: df505ac4c42977284ce5a0b2329d5556990c39c8

The fix will be present after version 0.1.74.
