### ISSUE TITLE
Blueprint page does not allow access to store

### ISSUE THREAD

**Issue by tehstun** [Adam13531/BotLand#11]
**Steps to reproduce**
Edit bot --> Click Store

**Expected outcome**
Opens the store page for buying items

**Actual outcome**
Does nothing

**Bowser information**
{"name":"Chrome","chrome":true,"version":"55.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 21
Player name: digi

**Comment by HiDeoo** [comment]
Any error /output in the console when clicking on the "Store" button?

**Comment by tehstun** [comment]
Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().

**Comment by Adam13531** [comment]
Fixed.

Commit hash: 559dac8712c1030608b989520c89c6427e74ef62
Version available: 0.1.20+
