### ISSUE TITLE
Haste chip thumbnail displays in place of bots in Edit Defense mode

### ISSUE THREAD

**Issue by shrmpy** [Adam13531/BotLand#112]
**Steps to reproduce**
Go to Edit Defense button. Choose Chips tab. Choose Haste item. Choose Bots tab and return to Bots list. Choose a existing bot. Inspect the image in the bottom of screen.
 Screen grab:
![screenshot from 2017-10-30 16-41-56](https://user-images.githubusercontent.com/24621188/32201223-a608fc3a-bdcd-11e7-8ce7-6b5fb1f47f14.png)

**Expected outcome**
Thumbnails show current selection.
**Actual outcome**
Thumbnail continues to show Haste chip.
**Browser (and version)**
Both Chromium and Firefox
**Operating system (and version)**
Linux

**Comment by Adam13531** [comment]
This will be fixed after version 0.2.102 (finally).
