### ISSUE TITLE
Wrong error message on short password modification

### ISSUE THREAD

**Issue by SilverMatch** [Adam13531/BotLand#115]
**Steps to reproduce**
Click on "Change password" on play.bot.land
Enter "Username"
Enter "Current password"
Enter a short (3 characters here) "New password"
Enter the same short password "Confirm new password"
Click "Change Password"

**Expected outcome**
Get an error saying that the password doesn't match minimum criteria (and gives the criteria)

**Actual outcome**

![error](https://user-images.githubusercontent.com/8248026/32459172-187eb2a8-c32f-11e7-8648-f75003f9c06b.png)

**Workaround**
Add a few characters to the new password and the modification is accepted

**Browser (and version)**
Chrome

**Operating system (and version)**
Windows 10

**Comment by Adam13531** [comment]
This was fixed a while ago; can't repro it now.
