### ISSUE TITLE
x of x placed button not aligned correctly

### ISSUE THREAD

**Issue by joeypothoff** [Adam13531/BotLand#122]
**Steps to reproduce**
1. Press Attack
2. Click 'Another player' and press Attack
3. 'See x of x placed' button.

**Expected outcome**
Aligned next to each other.

**Actual outcome**
2 lines with text (https://imgur.com/TEhwxrC)

**Browser information**
{"name":"Chrome","chrome":true,"version":"61.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 7
Player name: joey

**Comment by Adam13531** [comment]
Changed the entire UI for phase controls so that it looks like this now:
![image](https://user-images.githubusercontent.com/7192897/39488892-96799446-4d38-11e8-96e6-cfccc019e8c8.png)
