### ISSUE TITLE
UI - Not easy to remove an individual already placed bot

### ISSUE THREAD

**Issue by Nimtzwil** [Adam13531/BotLand#123]
Less a bug and more a UI issue

Issue:
In either attack or defense once a bot has been placed the only way to remove an individual bot is to clear the whole board (thats inconvenient) or attempt to place the same type of bot on the same location (thats not explained/ is unintuitive(imo))

Expected Outcome:
A simpler way to remove an individual bot that has already been placed. Perhaps a remove button on the panel that pops up when selecting an individual bot that has already been placed.

**Browser information**
{"name":"Chrome","chrome":true,"version":"61.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 164
Player name: Adrift

**Comment by Adam13531** [comment]
@Nimtzwil I'm just leaving a quick comment here without making a decision yet, but you can do this:
![2017-11-08_10-28-39](https://user-images.githubusercontent.com/7192897/32567336-d4b91634-c46f-11e7-8d40-8e716f3bb094.gif)

1. Long-press a bot (you have to hold the mouse down for longer than you may think)
2. Drag it out of the Arena

I know that *also* isn't explained in the game. The tutorial has gone through a ton of changes already and is still not as effective as it can be. :(

**Comment by Adam13531** [comment]
While nothing has been done since my last comment to make this any clearer in the game, I don't have plans to change this for now, so I'm going to close the issue.
