### ISSUE TITLE
Converting back from JS button problem

### ISSUE THREAD

**Issue by fangsrock12345** [Adam13531/BotLand#124]
**Steps to reproduce**
make code stuff (mine was update = function () {
    if (canReflect()) {
        reflect();
    }
    if (willLasersHit(item)) {
        fireLasers(item);
    } else {
        move('up');
    }
    if (!canMove('up')) {
        move('right');
    }
}; if that helps, convert to JS,press the button to prettify it.
**Expected outcome**
go back to the blocky
**Actual outcome**
stays in JS
**Browser information**
{"name":"Chrome","chrome":true,"version":"61.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 266
Player name: BoopyDoopy1

**Comment by HiDeoo** [comment]
Converting from JS to Blockly is not supported at the moment and I think it'll never be.

If the steps to reproduce are correct, *Prettify* does not render pretty the code by switching it back to a Blockly syntax but literally render the code pretty.

For example, having as code:

```js
update = function () { if (canMove()) { move(); }};
```

Using *Prettify* would give the following code:

```js
update = function () {
    if (canMove()) {
        move();
    }
};
```

Altho, if your code is already prettified, you might not notice any change at the moment as the operation completion is not indicated in any way.

**Comment by Adam13531** [comment]
For now, the Prettify button is gone entirely, but also, there's now a clear warning when you switch from Blockly to JS:

![image](https://user-images.githubusercontent.com/7192897/39489065-1e3c1bc4-4d39-11e8-95ea-bac21c91cd4f.png)

(note: the wording may change)
