### ISSUE TITLE
Keys 1, 2 and 3 are prevented by the lobby inside the Store, Settings and other modals

### ISSUE THREAD

**Issue by DennisRas** [Adam13531/BotLand#127]
I wasn't around when shortcuts were implemented, so I don't know if there are more key event listeners than just the 3 numbers.

**Steps to reproduce**
- Go to the lobby
- Open Settings, Store or any other dialog with the lobby in the background
- Focus an input element (Filters, Search, Forms, ...)
- Press the keys 1, 2 or 3

**Expected outcome**
- Normal typing in whatever input you're focusing 

**Actual outcome**
- Keys pressed are prevented
- Tabs in the lobby changes

![](https://i.imgur.com/SMWOryR.gif)

**Browser information**
{"name":"Chrome","chrome":true,"version":"62.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 4
Player name: Liquidor

**Comment by Adam13531** [comment]
@DennisRas good find! I just fixed this bug by calling stopPropagation from popups.

Commit hash: 7fae44fcbd16befc095fb5830ac464cbd804dc65
Available after version: 0.2.10.
