### ISSUE TITLE
Botcoin icon is missing padding

### ISSUE THREAD

**Issue by DennisRas** [Adam13531/BotLand#128]
**Steps to reproduce**
- Login
- Inspect the element/icon

**Expected outcome**
- Padding between the botcoin icon and the amount

**Actual outcome**
- No padding ☹

![](https://i.imgur.com/fRRzbn1.png)

Reference:
![](https://i.imgur.com/jJ8zuN9.png)

**Browser information**
{"name":"Chrome","chrome":true,"version":"62.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 4
Player name: Liquidor

**Comment by Adam13531** [comment]
This was intentional; I wanted Botcoin to feel like a currency, so this is almost like I'd put "$22" in that section instead of the Botcoin symbol and then "22".
