### ISSUE TITLE
Move cursor on main page

### ISSUE THREAD

**Issue by boleknowak** [Adam13531/BotLand#130]
**Steps to reproduce**
- Go to Attack player
- Click Attack
- Play all Phase
- Click Minimize button in results
- Click Show Results button
- Click Minimize button
- Click Cancel (exit to main menu)

**Expected outcome**
Maybe you must reset cursor in pages.

**Actual outcome**
![image](https://user-images.githubusercontent.com/8493474/32689225-9fb1619e-c6e0-11e7-80da-2590aa576033.png)

**Browser information**
{"name":"Chrome","chrome":true,"version":"61.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 310
Player name: boleknowak

**Comment by HiDeoo** [comment]
Thanks for the report.

I can't reproduce using these exact same steps (maybe the cursor needs to hover something or be changed in a specific way, like moving and dragging a bot or something) but I can definitely confirm this is a bug and globally there are multiple places / scenarios in Bot Land where this issue can happen and where `cursor` should be enforced.

Related issue: #39 .

**Comment by HiDeoo** [comment]
This seems to no longer be an issue, feel free to re-open if that's not the case for you.
