### ISSUE TITLE
Alignment issue on search/find bars for cosmetics and hardware

### ISSUE THREAD

**Issue by Adam13531** [Adam13531/BotLand#133]
This is pretty straightforward:
![image](https://user-images.githubusercontent.com/7192897/32693832-5069f712-c6e6-11e7-8793-e7c2d3e006d6.png)

The search box doesn't line up with the edges of the component beneath it. I just never did the work to address this.

**Additional information**
Originally filed by BIueberryKing on Twitch.

**Comment by HiDeoo** [comment]
This should be fixed in `v0.2.53`.
