### ISSUE TITLE
More intuitive way to place bots

### ISSUE THREAD

**Issue by ifohancroft** [Adam13531/BotLand#149]
If we place an attack bot on top of another attack bot, the bot dissapears and then we can place a bot again where we want. This is not an obvious way to rearrange attack bots.
Maybe make it so we can rearrange attack bots after we've placed them without having to drag an attack bots on top of them. (Same for the defense bots)

**Comment by Adam13531** [comment]
@ifohancroft I made this video just now because people have been asking about this sort of thing: https://youtu.be/D2mHVQ9V754

I'm going to close the issue under the assumption that the video addresses your concerns. If not, ping me on Twitch and I can reopen this.
