### ISSUE TITLE
Forfeit button not disabled after using it.

### ISSUE THREAD

**Issue by HiDeoo** [Adam13531/BotLand#15]
**Steps to reproduce**

1. Start a game as an attacker using the "Attack" button.
2. Remove the first popup introducing the match.
3. Double click on the "Forfeit" button.

**Expected outcome**

Forfeit the match, get the *end of game* popup with the button to return to the News page.

**Actual outcome**

You get the *end of game* popup and an additional alert saying that a 500 error has been returned with no message.

The call to the `forfeit` API is being made twice, the first one works, the second one fails as you're no longer in a game.

**Possible fix**

Disable the "Forfeit" button as soon as you used it once.

**Bowser information**

{"name":"Chrome","chrome":true,"version":"57.0","blink":true,"mac":true,"a":true}

**In-game information**

Player ID: 9
Player name: tempJS

**Comment by Adam13531** [comment]
Fixed in version 0.1.4 (commit hash: ed738bfc8818bc839ce39f84ddd34677b5d048d4).
