### ISSUE TITLE
Ability to drag or at least drag-select the whole connected code block

### ISSUE THREAD

**Issue by ifohancroft** [Adam13531/BotLand#151]
Make it so we can select-drag code blocks or so we can duplicate the whole connected code block.
Currently, it's possible to only drag a single code "element" at a time and no drag-select possible.

**Comment by Adam13531** [comment]
I'm not totally sure I follow what it is you're asking for here. You can already drag many blocks at once in Blockly, you just need to start dragging from the "highest" block as shown in this GIF:

![2017-11-18_10-40-55](https://user-images.githubusercontent.com/7192897/32983668-0f8d99a8-cc4d-11e7-883c-052dcf364ec8.gif)

As for duplicating blocks, that works differently; you can only seem to duplicate a "single" block at a time:

![image](https://user-images.githubusercontent.com/7192897/32983683-5e0365ea-cc4d-11e7-811c-32f377bd8b88.png)

If you find yourself duplicating large amounts of blocks many times, I wonder if you'd be better served by being able to save your own snippets for later use (a feature that I'd like to eventually implement). In the meantime, you can work around this by adding any blocks you want to duplicate to the same "single" element:

![2017-11-18_10-45-14](https://user-images.githubusercontent.com/7192897/32983695-964ed8ee-cc4d-11e7-968b-3c082dda79f9.gif)

In this GIF, you can see that I can only duplicate the comment block at the top by right-clicking. However, if I drag the entire script into another "if" block, then I can duplicate the whole script and later just get rid of the unnecessary "if" block.

**Comment by Adam13531** [comment]
I'm going to close this since "fixing it" would involve an overhaul of Blockly essentially.
