### ISSUE TITLE
More intuitive way to change avatar bot

### ISSUE THREAD

**Issue by ifohancroft** [Adam13531/BotLand#152]
In the avatar/bot edit, make it so we can change the current body parts by just clicking on the new ones we want to use.
Even though I've used the current method once, it took me a while the second time to figure out why I can't change the body and how to change it.

**Comment by Adam13531** [comment]
The UI that I'm screenshotting below is going to change, but for now it *does* say to drag an item to the slots to equip them:

![image](https://user-images.githubusercontent.com/7192897/39489909-ed232dc2-4d3b-11e8-94c1-f74e8bd768c1.png)

If I get this kind of feedback repeatedly, I may reopen the issue and try to find a more amenable way to equip items, but I don't think it's a big problem right now.
