### ISSUE TITLE
Blocky code converted to JS, no longer visible as blocks

### ISSUE THREAD

**Issue by ifohancroft** [Adam13531/BotLand#153]
**Steps to reproduce**
1). Make some code by arranging blocks
2). Click Convert to JS
3). Go the the JS tab.
4). Hit the update/save (can't remember what was written on the button) button
5). Go back to the block code tab
6). No blocks whatsoever.

Optional Steps:
7). Go back to the JS tab and hit Prettify code
8). Go back to the block code tab
9). Code blocks still not there

**Expected outcome**
To have the code block still there.

**Actual outcome**
No code blocks there.

**Browser (and version)**
Firefox 54.0 (64-bit)

**Operating system (and version)**
Fedora MATE 24 x86_64

**Comment by HiDeoo** [comment]
As far as I know, this is expected behaviour as you can only get one or the other and while converting to JS from Blockly is actually possible, the other way is not possible (and would probably never be).

**Comment by Adam13531** [comment]
I'm going to copy/paste what I said for #124 here:

There's now a clear warning when you switch from Blockly to JS:

![image](https://user-images.githubusercontent.com/7192897/39489065-1e3c1bc4-4d39-11e8-95ea-bac21c91cd4f.png)

(note: the wording may change)
