### ISSUE TITLE
RATE_LIMITED_FOR_MATCHMAKING

### ISSUE THREAD

**Issue by tehstun** [Adam13531/BotLand#16]
**Steps to reproduce**
play the game fast, winning games quick
**Expected outcome**
continuing to play :( or a prompt saying to slow down
**Actual outcome**
nothing but console output of "RATE_LIMITED_FOR_MATCHMAKING"
**Bowser information**
{"name":"Chrome","chrome":true,"version":"55.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 21
Player name: digi

**Comment by Adam13531** [comment]
Fixed in version 0.1.1 - rate-limiting decreased from 10s to 2s.
