### ISSUE TITLE
Possible to play without account activation.

### ISSUE THREAD

**Issue by GELight** [Adam13531/BotLand#165]
**Steps to reproduce**
1. Created an account
2. Played any matches.

**Expected outcome**
- NOT POSSIBLE to login or play anything without email activation.

**Actual outcome**
- POSSIBLE to login or play anything without email activation.

**Browser information**
{"name":"Chrome","chrome":true,"version":"63.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 784
Player name: GELight

**Comment by Adam13531** [comment]
This isn't actually a bug (but thank you for filing nonetheless!). You're given three days to verify your email address before you'll be forced to verify it (i.e. at that point, you won't be able to log in or do most things in the game). I wanted to reduce the friction between a person not knowing about Bot Land to playing.
