### ISSUE TITLE
Suggestion: Compact battle log for mobile

### ISSUE THREAD

**Issue by TwitchNomad** [Adam13531/BotLand#169]
If vertical space becomes an issue (or anyway) i personally like this kind of a design would be nice for a battle log that does not need any scrolling.

![botland-suggestion-final](https://user-images.githubusercontent.com/36651021/36609565-f60cfc00-18d5-11e8-85d6-e4a23d903eb6.png)

This is quite quickly made so it does not consider things such as long names, exact styling or a battle log header/title placement.

**Comment by Adam13531** [comment]
There's a lot of potential information to include in the battle log, and while having a very compact form could be beneficial in the long run, it's not planned for right now, so I'm closing this. For reference, here's a mock-up of the mobile version:

![image](https://user-images.githubusercontent.com/7192897/39491599-c5b85d6a-4d41-11e8-9b4f-73410c075334.png)

As you can see, the battle log doesn't show many entries, but I'm hoping it won't be much of a problem.
