### ISSUE TITLE
Edit Defense doesn't load current defense

### ISSUE THREAD

**Issue by Daxaar** [Adam13531/BotLand#17]
**Steps to reproduce**
1. Created and tested a defense.
2. Saved this defense and saw this being used against a number of other players successfully.
3. Purchased teleport in store.
4. Click Edit Defense.
 
**Expected outcome**
  Game board shown with existing defense loaded.
**Actual outcome**
  Empty game board shown (custom bots are still available).

**Bowser information**
{"name":"Chrome","chrome":true,"version":"55.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 33
Player name: Nadaar73

**Comment by Daxaar** [comment]
I can now repro this by clicking the Cancel button (bottom left of the game board) **after** successfully saving a defense.  I guess this is more of a UX issue as it's not obvious how you get back to the Battle Log screen after saving a defense.

**Comment by Adam13531** [comment]
Sorry for getting to this so late. I have a feeling that this bug is gone since I haven't heard any reports about it in the last month and a half. If you see it pop up again, let me know.
