### ISSUE TITLE
Context Bar persists between defense and attack

### ISSUE THREAD

**Issue by Skedog** [Adam13531/BotLand#176]
**Steps to reproduce**
Edit your defense
Click a chip in your arena
Change it to a different chip (or replace it with the same type)
Exit your defense
Click attack

[GIF of repro](https://gyazo.com/dc373c63576a9927395483fe421550ab)

**Expected outcome**
Context Bar doesn't exist in the arena

**Actual outcome**
Context Bar still exists and shows "broken" chip data

**Browser information**
{"name":"Chrome","chrome":true,"version":"65.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 2
Player name: Skedog

**Additional Info**
I think this all ties into the bug regarding the context bar and chips that is already known about - and seems pretty similar to #61

**Comment by Adam13531** [comment]
This will be fixed after version 0.2.102 (finally finally).
