### ISSUE TITLE
Forbidden action from public attack links

### ISSUE THREAD

**Issue by Skedog** [Adam13531/BotLand#177]
**Steps to reproduce**
Be in an existing match
Try to paste in a public attack link
Click attack
Click either resume or okay in the pop-up about being in an existing match

**Expected outcome**
Go to existing match or close the dialog

**Actual outcome**
Another popup saying "Unhandled Error" forbidden
![](https://i.gyazo.com/3521c72ee3273fc6d6b078fc58b1b8d0.png)

**Browser information**
{"name":"Chrome","chrome":true,"version":"65.0","blink":true,"windows":true,"a":true}
![](https://i.gyazo.com/f55979558c831298a8155b5e209d2fca.png)

**In-game information**
Player ID: 2
Player name: skedog

**Comment by Adam13531** [comment]
Fixed; I was accidentally throwing an error that I already handled. The fix should be present beyond version 0.2.26.

Commit hash: 2823d2898b8dba86465d9cb56771db479937bf6b
