### ISSUE TITLE
When a match ends, if you click the background it starts another attack

### ISSUE THREAD

**Issue by Skedog** [Adam13531/BotLand#178]
**Steps to reproduce**

- End a match
- Click on the semi-transparent background
![](https://i.gyazo.com/fbc752baa74135ae4d431a3eef1bf733.png)

**Expected outcome**
Either close the dialog (minimize) - or do nothing. This came to light because I did a private attack link match, I went to close that dialog, accidentally clicked on this background, and got put into a new, real match. This meant I then couldn't do another private attack link because I was already in a new match.

**Actual outcome**
Closes the dialog and starts another attack

**Comment by Adam13531** [comment]
Note to self: change AttackDetails so that there's "onConfirm" and "onClickOutside", and for pre-attack, it would be the same thing, but for MatchResults, they would be different.

**Comment by Adam13531** [comment]
Fixed. Commit hash: ddb1b0b3fb1a3e6b46731e7b3ddee7a141119a4c

The fix should be present after version 0.2.20.
