### ISSUE TITLE
In Safari You Cannot See The Bottom Of The Game

### ISSUE THREAD

**Issue by Xtrouble** [Adam13531/BotLand#179]
**Steps to reproduce**

Launch the game in safari

**Expected outcome**

You can play perfectly

**Actual outcome**

![screen shot 2018-04-06 at 14 16 46](https://user-images.githubusercontent.com/38140929/38437868-d13b4aca-39a6-11e8-9513-b23f6315dbc8.png)
![screen shot 2018-04-06 at 14 17 07](https://user-images.githubusercontent.com/38140929/38437869-d14848c4-39a6-11e8-8121-5146d51443de.png)
![screen shot 2018-04-06 at 14 21 21](https://user-images.githubusercontent.com/38140929/38437870-d1560da6-39a6-11e8-9cf2-0a2a694aae6e.png)
![screen shot 2018-04-06 at 14 21 39](https://user-images.githubusercontent.com/38140929/38437871-d162fd22-39a6-11e8-83f4-af21b40c01fe.png)

You won't be able to see part of the game in some areas... For example, in a match everything scales perfectly, when you end a match the buttons to continue and go back are off screen except you make the window more tall than wide... and in the menu the buttons in the bottom part are off screen even if you change the window size and shape...

**Browser (and version)**

Safari Version 10.1.2

**Operating system (and version)**

Mac OS X Yosemite Version 10.10.5

**Comment by HiDeoo** [comment]
Can reproduce in Safari 11 too.

**Comment by Xtrouble** [comment]
oh and also in safari you don't seem able to change the bots code with the blocks

**Comment by HiDeoo** [comment]
> oh and also in safari you don't seem able to change the bots code with the blocks

This specific bug should be fixed in the next version.

**Comment by HiDeoo** [comment]
The original issue should also be fixed in the next version.
