### ISSUE TITLE
Can't scroll in JS script editor. Firefox

### ISSUE THREAD

**Issue by patriqdesigns** [Adam13531/BotLand#18]
**Steps to reproduce**
Go to script editor, JS tab and type in a bunch of stuff, long enough so it gives you the option to scroll.

**Expected outcome**
You can scroll, and exit.

**Actual outcome**
The editor fills your whole screen and you are not allowed to either scroll or exit.

**Bowser information**
{"name":"Firefox","firefox":true,"version":"51.0","gecko":true,"windows":true,"a":true}

**In-game information**
Player ID: 971
Player name: patriqdesigns

**Comment by HiDeoo** [comment]
Same issue using `{"name":"Safari","safari":true,"version":"10.0","webkit":true,"mac":true,"a":true}`.

**Comment by bwfcwalshyPluginDev** [comment]
Cannot confirm using Chrome
{"name":"Chrome","chrome":true,"version":"55.0","blink":true,"windows":true,"a":true}

**Comment by HiDeoo** [comment]
This seems to be fixed in Safari as of today, but can still confirm this is an issue in Firefox (57.0b11).

**Comment by Adam13531** [comment]
Fixed. Commit hash: d206953732a080ba38accb406f89ff1a9c546952

Will be present in Beta.
