### ISSUE TITLE
Background not tiled properly

### ISSUE THREAD

**Issue by freaktechnik** [Adam13531/BotLand#183]
**Steps to reproduce**
 - Load play.bot.land in Chrome in landscape mode
 - Log in
 - Scroll down (to hide the nav bar)

**Expected outcome**
The background is tiled all the way.

**Actual outcome**
![image](https://user-images.githubusercontent.com/640949/38472858-943c8fbc-3b86-11e8-97af-00ae2aa15bb2.png)

The background is only tiled in the initially visible part of the viewport, not the part that becomes visible when scrolling away the nav bar.

**Browser (and version)**
Chrome 65.0.3325.109

**Operating system (and version)**
Android 8.1.0

**Comment by freaktechnik** [comment]
Currently not an issue anymore, since you simply can't scroll.

**Comment by HiDeoo** [comment]
This was still an issue on some devices on the login page, this should be properly fixed in `v0.2.52`.
