### ISSUE TITLE
Too Many Requests (Rate limiting problem)

### ISSUE THREAD

**Issue by Skedog** [Adam13531/BotLand#184]
**Steps to reproduce**

1. Have your password saved in Chrome
2. Refresh the page
3. Quickly double click the login button

**Expected outcome**
You get logged in

**Actual outcome**
You get a "too many requests" error along with an unknown error. I am double clicking due to the "login" button being disabled when you first visit the page, however I believe this is what causes the rate-limiting problem as well.

![](https://im2.ezgif.com/tmp/ezgif-2-dbd7dc3216.gif)

![](https://i.gyazo.com/c3940382876350780fb292eb0dce29b1.png)

**Browser information**
{"name":"Chrome","chrome":true,"version":"65.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 2
Player name: skedog
(Password: Yes, I changed it after making this gif because for whatever reason, that field also switches to text for me)

**Comment by Adam13531** [comment]
I confirmed that I can hit this on play.bot.land, but note to self: I may have disabled rate-limiting on localhost.

**Comment by Adam13531** [comment]
Fixed. Commit hash: c91e6666e036b6053df0b05e90fc79595ee9790c

The login button is now disabled when you click it and is re-enabled after the login works/fails.

This will be present after version 0.2.20.
