### ISSUE TITLE
Unhandled Error from store purchases

### ISSUE THREAD

**Issue by Skedog** [Adam13531/BotLand#185]
**Steps to reproduce**
Have less than needed amount of Bot Coin for a purchase
Try to buy something in the store

**Expected outcome**
Get a message about not enough Bot Coin and nothing else

**Actual outcome**
Get a message about not enough Bot Coin and then an internal server error
![](https://im2.ezgif.com/tmp/ezgif-2-664bf82a30.gif)
![](https://i.gyazo.com/1e21fcbbf6cba462a4e9eddcf1c0cc0a.png)

**Browser information**
{"name":"Chrome","chrome":true,"version":"65.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 2
Player name: skedog

**Comment by Adam13531** [comment]
This has been fixed (don't know the exact commit hash). The change will be present after version 0.2.26.
