### ISSUE TITLE
Gathering new token does not notify user to login again / refresh

### ISSUE THREAD

**Issue by tehstun** [Adam13531/BotLand#19]
**Steps to reproduce**
Head into any edit defence or update bots, sign in on another page or request a new token with the api, heading back to that old page and trying to save bots or update defence
**Expected outcome**
a message to state the user should refresh or login again to continue
**Actual outcome**
nothing
**Bowser information**
{"name":"Chrome","chrome":true,"version":"55.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 21
Player name: digi

**Comment by Adam13531** [comment]
Just commenting here that this won't be fixed for a while.

**Comment by tehstun** [comment]
Any update on this existing issue?

**Comment by Adam13531** [comment]
This was fixed as of version 0.2.93 (live now).
