### ISSUE TITLE
Blockly no longer usable in Safari 

### ISSUE THREAD

**Issue by HiDeoo** [Adam13531/BotLand#195]
**Steps to reproduce**

1. Go to Blockly

**Expected outcome**

Use Blockly to drag any block.

**Actual outcome**

No block are draggable.

The console report the following warning when attempting to drag a block.

![screen shot 2018-04-25 at 01 28 55](https://user-images.githubusercontent.com/494699/39218980-134308b0-4828-11e8-9759-32ed953cb32c.png)

Note: this is **new** aka was not always the case.

**Browser information**

{"name":"Safari","safari":true,"version":"11.1","webkit":true,"mac":true,"a":true}

**In-game information**

Player ID: 38
Player name: incognito

**Comment by freaktechnik** [comment]
Did you mean: "Blockly no longer usable in Safari"?

**Comment by HiDeoo** [comment]
This should be fixed in the next version and was related to `pixi.js`.

**Comment by Adam13531** [comment]
FYI: "next version" means >0.2.48.
