### ISSUE TITLE
Forfeiting a match can crash the Account Server

### ISSUE THREAD

**Issue by Adam13531** [Adam13531/BotLand#2]
**Steps to reproduce**

1. Attack someone
2. Place bots such that you'll win the game (this probably works regardless of winning/losing if you're in phase 3)
3. Click "Commence"
4. Before the game can finish, click "Forfeit"

**Expected outcome**
Probably that you can't even click the "Forfeit" button when you're watching an attack play out.

**Actual outcome**
The Account Server crashes with:
```
error: Error forfeiting game for user #2: Error: Can't set headers after they are sent.
```

**Comment by tbodt** [comment]
This issue was fixed but adam couldn't find the comment button

**Comment by Adam13531** [comment]
I fixed this.

**Comment by tbodt** [comment]
woohoo
