### ISSUE TITLE
JS Editor height broken on Safari 

### ISSUE THREAD

**Issue by HiDeoo** [Adam13531/BotLand#20]
**Steps to reproduce**

1. Edit a script using the JS Editor.

**Expected outcome**

Have the text editor use the full height of the window and get a dark background in the whole page.

**Actual outcome**

The dark background is only wrapping the current text of the editor.

It looks like the height of the editor is not 100% on Safari but adjusted to the height of the actual content of the editor.

**Bowser information**

{"name":"Safari","safari":true,"version":"10.0","webkit":true,"mac":true,"a":true}

**In-game information**

Player ID: 9
Player name: tempJS

**Screnshot**

![screen shot 2017-01-30 at 20 38 03](https://cloud.githubusercontent.com/assets/494699/22438380/07d97dbe-e72c-11e6-892c-d124e6ef3117.png)

**Comment by Adam13531** [comment]
I'm not completely sure *when* this was fixed, but @HiDeoo verified that this is fixed in version 0.1.69.
