### ISSUE TITLE
Surviving bots from previous phases aren't properly removed in Full Test Mode

### ISSUE THREAD

**Issue by Pnoexz** [Adam13531/BotLand#201]
I'll use 3 attacking bots in each phase as an example, but I don't think this is related to computer size.

**Steps to reproduce**
* Enter Full Test Mode
* Have a non-zero number bots survive phase 1
* Start phase 2

**Expected outcome**
Surviving bots get removed from the arena

**Actual outcome**
Surviving bots stay in the arena.  "0 / 3 bots placed" text shown, but 3 bots visible in arena. You can place the bots for second phase, but can't start due to having 6 bots

![201-1](https://user-images.githubusercontent.com/3297901/39338973-c9a147c8-49b5-11e8-93cf-a9a21feb3453.png)
![201-2](https://user-images.githubusercontent.com/3297901/39338974-c9cd3360-49b5-11e8-95b4-8bf93963c4ab.png)
![201-3](https://user-images.githubusercontent.com/3297901/39338975-c9f0fe12-49b5-11e8-833d-a6fd1ac80281.png)

**Browser information**
{"name":"Firefox","firefox":true,"version":"59.0","gecko":true,"windows":true,"a":true}

**In-game information**
Player ID: 1090
Player name: Pnoexz

**Comment by Adam13531** [comment]
Fixed. Commit hash: c6d0eb55222e0dd143d57f505322e9264e2baa1f

Fix should be present after version 0.2.23.
