### ISSUE TITLE
Converting to JS discards Blockly data

### ISSUE THREAD

**Issue by Pnoexz** [Adam13531/BotLand#202]
This only happens with a new script (possibly new blueprint). This works as expected when the script was already saved.

**Steps to reproduce**
* Create new blueprint (in my case, a defense script)
* Do some blockly
* Convert to JS

**Expected outcome**
Existent blockly gets converted to JS

**Actual outcome**
JS content is just the update function signature, ie:

```
update = function () {
};
```

**Browser information**
{"name":"Firefox","firefox":true,"version":"59.0","gecko":true,"windows":true,"a":true}

**In-game information**
Player ID: 1090
Player name: Pnoexz

**Comment by HiDeoo** [comment]
Encountered on stream, need to check if this has been resolved already or just added to the TODO file.

**Comment by Adam13531** [comment]
Fixed. Commit hash: c4221b2a93130b33e24d6f450bb2b90137e55bd3

Fix will be present after version 0.2.23.
