### ISSUE TITLE
Open-salvage UI can show an entire bot instead of a single part

### ISSUE THREAD

**Issue by Adam13531** [Adam13531/BotLand#204]
**Steps to reproduce**
Not totally sure other than just opening a pack. I've had it happen on the very first pack that I open.

**Expected outcome**
Each picture on the left shows just the item it's trying to represent.

**Actual outcome**
![image](https://user-images.githubusercontent.com/7192897/39489639-1cd167ec-4d3b-11e8-838f-9914d204d409.png)

**Browser information**
{"name":"Chrome","chrome":true,"version":"65.0","blink":true,"windows":true,"a":true}

**Other information**
I found this as early as January 23rd, 2018.

**Comment by HiDeoo** [comment]
This is fixed as part of the open salvage pack UI that @Adam13531 is currently crafting.
