### ISSUE TITLE
Twitch stream status polling should not be client side

### ISSUE THREAD

**Issue by HiDeoo** [Adam13531/BotLand#207]
**Steps to reproduce**

1. Use the game

**Expected outcome**

Know if Adam's stream is online.

**Actual outcome**

Suggestion: Know if Adam's stream is online but the check is made on the client side using a `setInterval`. It could be wiser to do that regularly on the server and serve the response with the news items as news items already have a way to be provided to the client and we could avoid 1 extra request.

This could also be painful for mobile users and their data use. 

Same goes for you and your number of authorized requests to the API using your Client ID if the game gets huge.

**Browser (and version)**

All

**Operating system (and version)**

All

**Comment by freaktechnik** [comment]
Using webhooks on the server-side is indeed the more scalable, future proof way of doing this.

**Comment by Adam13531** [comment]
Thank you both for the feedback! 😃

Note that I haven't implemented webhooks yet in the back end, but at least the Overseer is what's doing the polling instead of the client.
