### ISSUE TITLE
updating to new token does not expire old token

### ISSUE THREAD

**Issue by tehstun** [Adam13531/BotLand#21]
* This could be used to damage others account if they get hold of the token, even after the user signs in again.

**Steps to reproduce**
Gather first token, use this for a request, get another token and use old token to make another request
**Expected outcome**
first token should be expired, stopping someone else still using your old token as you to damage your account
**Actual outcome**
first token still works perfectly fine.
**Bowser information**
{"name":"Chrome","chrome":true,"version":"55.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 21
Player name: digi

**Comment by HiDeoo** [comment]
Possibly related #19.

**Comment by Adam13531** [comment]
Just commenting here that this won't be fixed for a while.

**Comment by Adam13531** [comment]
This was sort of fixed as of version 0.2.93 (live now).

Technical details: your tokens, even if expired, can be refreshed to fetch new ones. However, if you change your password, expired tokens will stop working and you'll be forced to log in again on all devices.

After launch, these particulars may change, but this is likely how it'll be for launch.
