### ISSUE TITLE
Cloaked bot timedout and didn't uncloak for more than 5 turns

### ISSUE THREAD

**Issue by Pnoexz** [Adam13531/BotLand#214]
**Steps to reproduce**
I have no idea how this happened, but I was testing my own defense in Full Test Mode and one of my bots (Gamma) had a legit timeout.

https://i.gyazo.com/17136d9565237b7ed0b6ff2926cf1b8b.mp4

I tried to repro this with havocbot (replay 24151) but we couldn't get the same result.

After this happened, I also got #213, but it might not be related.

**Browser information**
{"name":"Firefox","firefox":true,"version":"59.0","gecko":true,"windows":true,"a":true}

**In-game information**
Client version: 0.2.26
Player ID: 1090
Player name: Pnoexz

**Comment by Adam13531** [comment]
Beyond version 0.2.26, timed-out bots will now be killed instantaneously. Also, I increased the timeout from 15ms to 25ms, but I still want to prevent them entirely somehow in the future (still in the works).
