### ISSUE TITLE
Sounds/Music not respecting volume levels

### ISSUE THREAD

**Issue by Skedog** [Adam13531/BotLand#217]
**Steps to reproduce**
1) Turn a volume slider all the way down
2) Move the "master" slider

**Expected outcome**
Volume respects what level their sliders are at

**Actual outcome**
Sounds/music will play regardless of individual slider volume (specifically if they are set to 0, music/sounds will still play).

**Browser information**
{"name":"Chrome","chrome":true,"version":"66.0","blink":true,"windows":true,"a":true}
(Also happens in FF, found by noisytofu)

**In-game information**
Client version: 0.2.26
Player ID: 2
Player name: skedog

**Comment by Adam13531** [comment]
Fixed. Commit hash: 1670413245888ca7dd316ae036c44101f27576c3

Fix will be present after version 0.2.26.
