### ISSUE TITLE
UI bug with volume sliders

### ISSUE THREAD

**Issue by Skedog** [Adam13531/BotLand#218]
**Steps to reproduce**
1) Open settings
2) Slide a volume slider

**Expected outcome**
Popup that says volume level should follow the slider as it moves

**Actual outcome**
Slider "number" stays in place
![](https://i.imgur.com/DQK5oqd.png)

**Browser information**
{"name":"Chrome","chrome":true,"version":"66.0","blink":true,"windows":true,"a":true}

**In-game information**
Client version: 0.2.26
Player ID: 2
Player name: skedog

**Comment by Adam13531** [comment]
This is due to this issue: https://github.com/react-component/align/issues/18

I'm going to wait for a fix on that first.

**Comment by HiDeoo** [comment]
As this is still an issue and the repository seems to no longer be maintained (14 pending PRs), I've workaround the issue and should be fixed in `v0.2.52`.
