### ISSUE TITLE
Invalid hardware layout in the Bot Inspector

### ISSUE THREAD

**Issue by HiDeoo** [Adam13531/BotLand#22]
**Steps to reproduce**

1. Attack.
2. Show the Bot inspector by clicking on a defense bot.

**Expected outcome**

Have a proper layout / sizing of the various hardware elements composing a blueprint.

**Actual outcome**

The sizing is either hard coded or invalid. If you have lots of hardware, the text explaining what the hardware is even doing is out of the box.

*Note: See the screenshot for more informations.*

**Bowser information**

{"name":"Chrome","chrome":true,"version":"57.0","blink":true,"mac":true,"a":true}

**In-game information**

Player ID: 9
Player name: tempJS

![screen shot 2017-01-30 at 20 56 51](https://cloud.githubusercontent.com/assets/494699/22439302/5a709f46-e72f-11e6-993d-2ed3bf9071c1.png)

**Comment by Adam13531** [comment]
This dialog no longer exists in the game. Also, as mentioned in #99, I now use shorter descriptions in cases like this.
