### ISSUE TITLE
Pinned app on iOS are not fullscreen

### ISSUE THREAD

**Issue by HiDeoo** [Adam13531/BotLand#223]
**Steps to reproduce**

1. Pin the app on iOS

**Expected outcome**

Have the app running in fullscreen mode.

**Actual outcome**

There is a top black bar.

https://cdn.discordapp.com/attachments/363267246900117516/451133789188653078/video.mov

**Browser (and version)**

Safari

**Operating system (and version)**

iOS 11.3.1

*This bug was initially reported by 3DExtended on Discord.*

**Comment by freaktechnik** [comment]
This would probably be solved by the "apple-mobile-web-app-*" meta tags: https://github.com/joshbuchea/HEAD#apple-ios

**Comment by HiDeoo** [comment]
This should be fixed in the next version.
