### ISSUE TITLE
Script ID still increases on temp scripts

### ISSUE THREAD

**Issue by tehstun** [Adam13531/BotLand#23]
could be used with bots to cap out your script id count (if you have any?)

**Steps to reproduce**
Call creation script api with temp script set as too, increases script id number

**Expected outcome**
not sure, shouldn't scripts that are temp not added to core script table? 
**Actual outcome**
increases script id count (ask me for gif)

**Bowser information**
{"name":"Chrome","chrome":true,"version":"55.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 21
Player name: digi

**Comment by Adam13531** [comment]
I changed almost everything to do with this code in the last week or so, which means this shouldn't be an issue anymore:
* Temporary IDs only exist on the client.
* Scripts only count toward your limit when they've been created on the server.
* The server no longer tells you what your limit is; everyone's is set to 16 for now.
