### ISSUE TITLE
Mobile - Cannot close settings page

### ISSUE THREAD

**Issue by hylh** [Adam13531/BotLand#232]
**Steps to reproduce**
Samsung Internett
1. Edit defense
2. Open Settings
3. Try to close settings

Chrome
1. Open settings
2. Try to close settings

**Expected outcome**
Seeing and being able to press the X to close the view.

**Actual outcome**
Cannot see or press the X to close the view. We cannot scroll the view.

In the Samsung Internett browser you can scroll the main page settings view, but not in Chrome.

![settings_close](https://user-images.githubusercontent.com/8884158/41379542-86bf3c80-6f62-11e8-8ac7-bf1e49b08f56.png)

**Browser (and version)**
Samsung Internett v. 6.4.10.5
Chrome 67.0.3396.87

**Operating system (and version)**
Android v. 7
Samsung Galaxy S7

**Comment by HiDeoo** [comment]
This is no longer an issue as this can only happens in portrait mode on small screen and now, we're showing a modal telling you to switch to landscape when this is the case.
