### ISSUE TITLE
League attack flag css "quirks"

### ISSUE THREAD

**Issue by ericthornton** [Adam13531/BotLand#237]
**Steps to reproduce**
1. Login with no league activity
2. Attack (and win)
3. Cancel post-attack dialog
4. Click 'Home' on bottom bar
5. Watch flag transition up the right sidebar.
6. See attached css "quirks"

**Expected outcome**
1. Flag would have seamless bottom
2. Flag would not have a dash in the arrow portion between "ATK" and number

**Actual outcome**
<img width="71" alt="flag" src="https://user-images.githubusercontent.com/3598033/42197316-350d5a00-7e50-11e8-8e11-69d474290e9d.png">

**Browser information**
{"name":"Chrome","chrome":true,"version":"67.0","blink":true,"windows":true,"a":true}

**In-game information**
Client version: 0.2.41
Player ID: 262
Player name: boatland

**Comment by HiDeoo** [comment]
This seems to no longer be an issue in the latest Chrome version. Feel free to re-open the issue if that's not the case for you.

![screen shot 2018-09-27 at 16 16 28](https://user-images.githubusercontent.com/494699/46152158-b7c3fa80-c270-11e8-86f7-d21b6b96fa88.png)
