### ISSUE TITLE
Deleting script shouldnt close panel

### ISSUE THREAD

**Issue by tehstun** [Adam13531/BotLand#24]
**Steps to reproduce**
Delete a script
**Expected outcome**
A delete button next to the UI that will allow you to quickly delete the script (with a prompt) while also prompting to close or open the following script for editing? 
**Actual outcome**
Closes the script editing panel
**Bowser information**
{"name":"Chrome","chrome":true,"version":"55.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 21
Player name: digi

**Comment by DennisRas** [comment]
Instead of loading up the next script (that won't fit the current bot being edited), maybe just create a new Unnamed script

**Comment by HiDeoo** [comment]
With the new UI, this is is no longer an issue. All credit goes to @Skedog for pointing that out.
