### ISSUE TITLE
Certain combinations of cosmetics make avatar float

### ISSUE THREAD

**Issue by Pnoexz** [Adam13531/BotLand#244]
**Steps to reproduce**
Go to edit avatar page in desktop mode (also happens in mobile, but it's less noticeable)
Add Sea Monster Head
Wrecking Ball/Ladybug Torso
Add something short (as opposed to tall) for Feet (octopus, air, engine, battery, bat, etc)

**Expected outcome**
![image](https://user-images.githubusercontent.com/3297901/44559711-2833a500-a722-11e8-8b77-b72c0b86a6f4.png)

**Actual outcome**
Bot seems to float.
![image](https://user-images.githubusercontent.com/3297901/44559705-210c9700-a722-11e8-8c9c-6c1adb9a55e6.png)
There's this pixel that only goes away when you replace Sea Monster Head. It doesn't change colors
![image](https://user-images.githubusercontent.com/3297901/44559780-8e202c80-a722-11e8-9679-028d0731deb3.png)

This also happens in the blueprint editor and in the arena (both on computer and in blueprint selector)
![image](https://user-images.githubusercontent.com/3297901/44559851-14d50980-a723-11e8-9a40-c63fc936f5f1.png)

**Browser information**
{"name":"Firefox","firefox":true,"version":"61.0","gecko":true,"windows":true,"a":true}

**In-game information**
Client version: 0.2.47
Player ID: 1090
Player name: Pnoexz

**Comment by Adam13531** [comment]
This was fixed a long time ago.
