### ISSUE TITLE
Jumping bots

### ISSUE THREAD

**Issue by 3DExtended** [Adam13531/BotLand#25]
**Steps to reproduce**
Get your iPad, open Safari and play a game. The bots are eventually jumping from one position to a field without interpolating between. Maybe a problem with speed and interpolation.

**Bowser information**
{"name":"Safari","safari":true,"version":"10.0","webkit":true,"ipad":true,"ios":true,"osversion":"10.2","tablet":true,"a":true}

**In-game information**
Player ID: 39
Player name: 3dextended

**Comment by HiDeoo** [comment]
Did the run use shaders or not? Could you try turning shaders off and check if the same behaviour is happening?

Also, what is your iPad model?

**Comment by 3DExtended** [comment]
Yes this bug is still happening. 
I have an iPad 2 with the newest firmware

**Comment by Adam13531** [comment]
Note to self: I asked 3DExtended about this in chat to find out whether it's possible it was due to Teleport hardware, and he said:

> 3DExtended: Right [they] were my own bots without teleport

**Comment by Adam13531** [comment]
Apparently this was never a bug, it was just Melee/charge:

1:15  3DExtended: @Adam13531 this can be closed
1:16  3DExtended: This was me not noticing something. It was the charge attack

**Comment by Adam13531** [comment]
FYI: I just made a commit (hash:  4272ef1c9de5880ca6ec665155bea594305aec06, available in version 0.1.20+) that should address lag while testing your defense. It only works while testing though, not while attacking.
