### ISSUE TITLE
Tutorial highlight makes white text less readable

### ISSUE THREAD

**Issue by freaktechnik** [Adam13531/BotLand#252]
**Steps to reproduce**
- Start attack tutorial
- Get to phase info step

**Expected outcome**
Steps are highlighted but background color stays the same, or text at least stays readable.

**Actual outcome**
![image](https://user-images.githubusercontent.com/640949/45154159-eb15eb00-b1d6-11e8-9056-b5fd772649bb.png)

Background color of highlighted area is lighter than the actual background color without tutorial overlay

**Browser (and version)**
{"name":"Firefox","firefox":true,"version":"64.0","gecko":true,"linux":true,"a":true}

**In-game information**
Client version: 0.2.48
Player ID: 25
Player name: freaktechnik

**Comment by Adam13531** [comment]
Fixed. Fix should be present after version 0.2.48. Commit hash: 1ec9573b3aca6f8fb2cfd158c8d55c472ff02119

Here's what it looks like now:
![image](https://user-images.githubusercontent.com/7192897/45238056-5625f700-b295-11e8-885b-a37c516f92f1.png)
