### ISSUE TITLE
Start label in tutorial buttons missaligned

### ISSUE THREAD

**Issue by freaktechnik** [Adam13531/BotLand#254]
**Steps to reproduce**
- Use niche indie browser
- Open tutorials dialog

**Expected outcome**
Button label should be centered on the tip of the play triangle.

**Actual outcome**
![image](https://user-images.githubusercontent.com/640949/45169297-9afe4f00-b1fd-11e8-8ddd-0a7cf57f919c.png)

It's not at all vertically centered.

**Browser information**
{"name":"Firefox","firefox":true,"version":"64.0","gecko":true,"linux":true,"a":true}

**In-game information**
Client version: 0.2.48
Player ID: 25
Player name: freaktechnik

**Comment by Adam13531** [comment]
This doesn't repro for me on version 62 on Windows. I'm not indie enough.
![image](https://user-images.githubusercontent.com/7192897/45238637-5d4e0480-b297-11e8-8659-e1949205d68a.png)

**Comment by freaktechnik** [comment]
This is at the very least a little better in the latest version:
![image](https://user-images.githubusercontent.com/640949/45866791-2a6d3b80-bd82-11e8-84b9-41b919859241.png)
