### ISSUE TITLE
Full defense test not working

### ISSUE THREAD

**Issue by Emessen** [Adam13531/BotLand#257]
**Steps to reproduce**
When testing defense there is the option of quick and full.
**Expected outcome**
Select full, place bots, hit check mark to start, and the test should begin.
**Actual outcome**
Hit check mark to start, and nothing seems to happen.
**Browser information**
{"name":"Firefox","firefox":true,"version":"62.0","gecko":true,"windows":true,"a":true}

**In-game information**
Client version: 0.2.48
Player ID: 2724
Player name: Extalos

**Comment by HiDeoo** [comment]
Associated error:

```js
```

**Comment by Adam13531** [comment]
Oh boy. 😳 Good find, @Emessen. I'm going to try to take a look at this on Friday's stream (i.e. <24 hours).

**Comment by Adam13531** [comment]
Found the issue. I'd changed a function to use an object for all of its arguments, but in refactoring the code, I left a variable with the wrong name, so the object would have a "missing" parameter.

Should be fixed after version 0.2.48. Commit hash: 0fd1ec749f9683f0355d4b6ce2dc3b36e665a1ce
