### ISSUE TITLE
Speed buttons don't show on mobile defense testing

### ISSUE THREAD

**Issue by Skedog** [Adam13531/BotLand#258]
**Steps to reproduce**
Open defense on iOS (might be others as well, I can only confirm iOS though)
Click the "test defense"

**Expected outcome**
Have buttons to speed up/slow down match the same as when attacking

**Actual outcome**
Buttons don't exist

**Browser information**
Pinned iOS page

**In-game information**
Client version: 0.2.48
Player ID: 2
Player name: skedog

**Comment by HiDeoo** [comment]
This should be fixed in `v0.2.53`.

![46347189-faa81880-c64a-11e8-9cd6-3fbbef2ac58f](https://user-images.githubusercontent.com/494699/46743844-32960800-ccaa-11e8-8cb5-9c7c13fbc7d1.gif)
