### ISSUE TITLE
When selected a bot on mobile, the context bar shows no hardware until the bot is placed

### ISSUE THREAD

**Issue by Skedog** [Adam13531/BotLand#259]
**Steps to reproduce**
Enter the arena
Select a bot you want to place

**Expected outcome**
Can see the hardware in the context bar

**Actual outcome**
Context bar is empty
![img_4997](https://user-images.githubusercontent.com/944977/45238066-862dc400-b2ae-11e8-83cc-0444e5a621be.PNG)

**Browser (and version)**
iOS pinned app

In-game information
Client version: 0.2.48
Player ID: 2
Player name: skedog

**Comment by HiDeoo** [comment]
This should be fixed in version 0.2.48.
