### ISSUE TITLE
Label for color change fee missing a space

### ISSUE THREAD

**Issue by freaktechnik** [Adam13531/BotLand#260]
**Steps to reproduce**
- Change colors of avatar
- Look at warning label below confirm button

**Expected outcome**
There's a space between the amount and "to".

**Actual outcome**
![image](https://user-images.githubusercontent.com/640949/45301785-e83a3380-b511-11e8-8ec9-c2f83e100862.png)

**Browser (and version)**

**Operating system (and version)**

**Comment by HiDeoo** [comment]
This should be fixed in `v0.2.52`.
