### ISSUE TITLE
Cant create account in Microsoft Edge

### ISSUE THREAD

**Issue by DuneganS** [Adam13531/BotLand#261]
**Steps to reproduce**
Visit https://play.bot.land/
Click on "Create An Account"
**Expected outcome**
Have the ability to create a Bot Land account
**Actual outcome**
Get redirected to the login page
**Browser (and version)**
Microsoft Edge (Version 42.17134.1.0)
**Operating system (and version)**
Windows 10

**Comment by Adam13531** [comment]
This has been fixed as of version 0.2.50. The problem was that the "Create account" button was being treated as the submit button for the login form because it didn't have `type="button"` on it.
