### ISSUE TITLE
Botcoin font issue

### ISSUE THREAD

**Issue by Sflyer5** [Adam13531/BotLand#264]
Not sure if this is a bug or not, the font for the botcoins looks distorted...
![bug](https://user-images.githubusercontent.com/43384761/45704191-3ff52200-bb44-11e8-9fb5-29fe80600edb.JPG)

**Comment by Sflyer5** [comment]
Oh, and first GIT post, Unsure how to mark this as a bug...

**Comment by freaktechnik** [comment]
You probably can't. This looks like the font is not loaded for the botcoin icon.

**Comment by HiDeoo** [comment]
@Sflyer5 	What do you mean exactly by *looks distorted*? When trying to zoom on the screenshot, I can't really identify what is wrong, or what you would have expected?

**Comment by HiDeoo** [comment]
I'm closing this at the moment due to lack of details, feel free to re-open if you have more details regarding what the issue is exactly if it's not even fixed yet.
