### ISSUE TITLE
Blank Black box on botland mobile and crashes after resuming from a suspended tab.

### ISSUE THREAD

**Issue by Sflyer5** [Adam13531/BotLand#265]
![wp_ss_20180918_0001](https://user-images.githubusercontent.com/43384761/45710593-18f31c00-bb55-11e8-8b84-c00ac9b9b606.png)

Upon loading the upgrade section, you get this black box.

Oh and automatically crashes the tab, when resuming from being suspended.

**Comment by HiDeoo** [comment]
Can you add your mobile, OS, etc. as it's mobile specific?

**Comment by Sflyer5** [comment]
And forgot to add the bug icon -_-, Phone information: Windows phone 10

**Comment by Sflyer5** [comment]
>           Can you add your mobile, OS, etc. as it's mobile specific?
Thanks for adding the bug label, Yes, windows 10 mobile, M.S Edge.

**Comment by HiDeoo** [comment]
This browser is no longer supported in Bot Land as Microsoft killed the project anw.

https://twitter.com/joebelfiore/status/917071399541391360
