### ISSUE TITLE
Rocket in attack button not centered

### ISSUE THREAD

**Issue by freaktechnik** [Adam13531/BotLand#268]
**Steps to reproduce**
- Click Attack button
- Accept player to attack
- Place some bots

**Expected outcome**
Attack confirmation button has a nicely centered black icon

**Actual outcome**
![image](https://user-images.githubusercontent.com/640949/46112810-36c31f80-c1ec-11e8-9af1-271fbd4a8552.png)

Icon is not centered and lower-contrast white.

**Browser information**
{"name":"Firefox","firefox":true,"version":"64.0","gecko":true,"windows":true,"a":true}

**In-game information**
Client version: 0.2.51
Player ID: 25
Player name: freaktechnik

**Comment by HiDeoo** [comment]
Note: this should use `ButtonPair` when integrated.

**Comment by HiDeoo** [comment]
This should be fixed in `v0.2.52`.
