### ISSUE TITLE
Store broken on Safari

### ISSUE THREAD

**Issue by HiDeoo** [Adam13531/BotLand#27]
**Steps to reproduce**

1. Go to the store

**Expected outcome**

Have a correct layout for the store and be able to use it.

**Actual outcome**

The layout is invalid and the store is not scrollable at all (the arrows and gutter icons do not work either).

*Note: If you need any help debugging this issue on Safari, just ping me @Adam13531*

![screen shot 2017-01-31 at 20 01 28](https://cloud.githubusercontent.com/assets/494699/22479980/16628ea6-e7f0-11e6-9ac0-a5b24954e2c0.png)

**Bowser information**

`{"name":"Safari","safari":true,"version":"10.0","webkit":true,"mac":true,"a":true}`

**In-game information**

Player ID: 9
Player name: tempJS

**Comment by HiDeoo** [comment]
This is now fixed with the new UI.

**Comment by Adam13531** [comment]
Thanks for checkin'.
