### ISSUE TITLE
Public Attacks Tutorial "Got It" button is wrong

### ISSUE THREAD

**Issue by Skedog** [Adam13531/BotLand#270]
**Steps to reproduce**
Get to the last step of the "public attacks" tutorial
Look at the "got it" button

**Expected outcome**
The "got it" button should be the gold/yellow color like all the rest

**Actual outcome**
It's the gray color (Seems you have this button as a "skip button" vs a "done button")

![](https://i.imgur.com/Aa91mTg.png)

**Comment by Skedog** [comment]
As I test more, this bug is also present at the end of the "Edit defense" tutorial:

![](https://i.imgur.com/7caSoYX.png)

**Comment by HiDeoo** [comment]
This should be fixed in `v0.2.52`.
