### ISSUE TITLE
Inconsistent back to home button icon

### ISSUE THREAD

**Issue by freaktechnik** [Adam13531/BotLand#273]
**Steps to reproduce**
- Start match, remember button to go back to home
- End match, remember button to go back to home

**Expected outcome**
Both buttons have the same icon, so either the arrow to the left or the home. I feel like the home button is a bit more accurate, since the "back" button doesn't take you to your last match, for example, when playing consecutive matches.

**Actual outcome**
The attack screen has an arrow to the left icon, the post match screen has a home icon.

**Browser information**
{"name":"Firefox","firefox":true,"version":"64.0","gecko":true,"linux":true,"a":true}

**In-game information**
Client version: 0.2.52
Player ID: 25
Player name: freaktechnik

**Comment by HiDeoo** [comment]
This may involves Jason as the mockup for pre-attack clearly uses a *back* icon while the post-attack one uses the *home* one.

**Comment by Adam13531** [comment]
Got a response from Jason; the 🏠 button is what we should use here.

**Comment by HiDeoo** [comment]
This should be fixed in `v0.2.53`.
