### ISSUE TITLE
Attack Intro Tutorial - unable to perform step tap enemy bot

### ISSUE THREAD

**Issue by illgitthat** [Adam13531/BotLand#276]
**Steps to reproduce**
Create new account
Proceed with default tutorial (attack introduction)
**Expected outcome**
Click enemy bot to move on to next step of tutorial.
**Actual outcome**
Receive generic tutorial error 'this action is disabled for now while you're completing...' 'To proceed with this tutorial tap an enemy bot to see what it has equipped.'
**Browser (and version)**
Google chrome Version 69.0.3497.100 (Official Build) (64-bit)
**Operating system (and version)**
Windows 10

**Comment by HiDeoo** [comment]
From Twitch chat:

> Going crazy here though... I clicked a bunch of times, exited the tutorial, reproduced it... then i was just in the process of making a screen grab and i can't reproduce it.

**Comment by illgitthat** [comment]
I'm fairly confident this is an issue because I reproduced it three separate times but it seems really inconsistent - haven't been able to get a recording of it.

Basically - I clicked around on screen (tried each bot on the page) but kept getting that error message.

**Comment by illgitthat** [comment]
Okay, finally got it captured here. I don't have time to figure out what the pattern is but my only guess is maybe investigate if this has to do with a previous half completed tutorial action.

I originally encountered this bug on the following workflow:

1. Deleted account that had played maybe part of a game
2. Created new account and entered tutorial immediately
3. Encountered bug

![276 Example](https://user-images.githubusercontent.com/2256474/46426573-f80df780-c70c-11e8-9f4a-737ae5945c4b.gif)

**Comment by Adam13531** [comment]
I believe the cause is long-pressing the bot instead of a short press.

**Comment by illgitthat** [comment]
Yes that was it. Reproducible under following circumstances:
Tapping (using touchscreen): No
Clicking (pressing down on laptop trackpad): No
Tapping (using trackpad): Yes

I'm using an hp spectre x360.

**Comment by Adam13531** [comment]
This tutorial no longer exists, but the issue existed in the new tutorial that I added, so I fixed it there. Commit hash: c6cd9a758ed5e9e8260989ac33397fbdf780109d.
