### ISSUE TITLE
Store popup too high/tooltips not cleaned up

### ISSUE THREAD

**Issue by freaktechnik** [Adam13531/BotLand#279]
**Steps to reproduce**
- Once again, dust off Firefox, haven't tried this in any other browser, because being ignorant is what humans do best.
- Have a couple tooltips shown, probably some from the arena or whatever (since the screenshot shows "commence game" tooltips)
- Open store

**Expected outcome**
Store is constrained to the viewport.

**Actual outcome**
Store popup goes out of the viewport. This is due to the body being higher than the viewport - from looking at the inspector I'd guess it's some tippy tooltips or some random empty divs that are at the end of the document (I assume from react-router for routes that aren't active or similar).

Since the body is the only non-static ancestor is the body that has position fixed, the popup with position absolute that has distance 0 from any of the non-static parent's bounding box gets the size of the body, leading to inaccessible parts of the popup.

As you can see in this full-page screenshot I took in Firefox it's some tooltips that stuck around that caused this issue:
![image](https://user-images.githubusercontent.com/640949/46908982-751a4780-cf2b-11e8-8dff-c0072b397671.png)

The following is a screenshot of the inspector, showing the tippy divs:
![image](https://user-images.githubusercontent.com/640949/46909001-b01c7b00-cf2b-11e8-822d-3600023b447e.png)

The empty divs at the end just contain another empty div and that's it, so they're completely irrelevant and just random garbage from not using fragments, I assume.

It's very much possible this will already be fixed in the next version, but filing for completeness.
I also assume that's what some people in Twitch chat had issues with on Friday.

**Browser information**
{"name":"Firefox","firefox":true,"version":"64.0","gecko":true,"linux":true,"a":true}

**In-game information**
Client version: 0.2.54
Player ID: 25
Player name: freaktechnik

**Comment by HiDeoo** [comment]
Notes for me for later when fixing it:

- The extra tooltips are fixed in master.
- The extra divs should be removed and will be an easy fix.
- Maybe add some kind of mechanism to prevent that even if it shouldn't happen with the fix in master?

**Comment by HiDeoo** [comment]
This should be fixed in `v0.2.55`.
