### ISSUE TITLE
Audio distorted in Firefox on iOS

### ISSUE THREAD

**Issue by Magentah** [Adam13531/BotLand#281]
**Steps to reproduce**
Open Botland and play audio.

**Expected outcome**
Audio plays.

**Actual outcome**
Audio is distorted

**Browser (and version)**
Firefox Version 14.0 (12646)

**Operating system (and version)**
iOS 12.0.1 - iPhone 6

**Comment by HiDeoo** [comment]
Would you be able to get a recording of the distorted audio as I can't repro, altho the oldest iPhone I can get is an iPhone 6s so maybe that's the reason I can't get the repro?

**Comment by Magentah** [comment]
I'm unable to recreate the issue now after loading the site in safari where it worked fine, so I guess this can be closed now.
