### ISSUE TITLE
Graphics glitch in top-left corner during battle

### ISSUE THREAD

**Issue by rhymu8354** [Adam13531/BotLand#285]
**Steps to reproduce**

1. Attack someone.
2. During battle, watch the top-left corner of the board.

**Expected outcome**

I should not see any glitches in the corner.

**Actual outcome**

There is some kind of glitch, like a small smoke cloud or explosion.

**Browser (and version)**

Firefox 64.0

**Operating system (and version)**

Windows 10.0.17134.345

** Screen Shot (problem highlighted) and Video Capture **

![botland-1](https://user-images.githubusercontent.com/41497796/50017247-6e866b80-ff80-11e8-8852-274193585049.png)
![botland-1](https://user-images.githubusercontent.com/41497796/50017255-70e8c580-ff80-11e8-8ec6-4559260ee992.gif)

**Comment by Adam13531** [comment]
This will be fixed in the next version of Bot Land (hopefully 0.2.61).
