### ISSUE TITLE
UI bug: Music playing while showing muted

### ISSUE THREAD

**Issue by FletcherCodes** [Adam13531/BotLand#287]
**Steps to reproduce**

- Create account

**Expected outcome**

Music is playing, and the music icon on the tutorial box shows that it's un-muted. When you hover over it, it says "Mute".

![image](https://user-images.githubusercontent.com/44245838/50018152-3b66cb00-ffc6-11e8-8956-1a0ebc2b7f8c.png)

**Actual outcome**

Music is playing, and the music icon on the tutorial box shows that it is muted. When you hover over it, it says "Unmute".

![image](https://user-images.githubusercontent.com/44245838/50018165-47528d00-ffc6-11e8-9cc3-f235ba9ff7da.png)

**Browser (and version)**

Google Chrome - Version 70.0.3538.110 (Official Build) (64-bit)

**Operating system (and version)**

Windows 10 - Version 1803 (OS Build 17134.471)

**Comment by talk2MeGooseman** [comment]
I had the same issue but instead of the icon being in the "Music Playing" state it was instead in the "Muted" state. That clicked it went to the "Music Playing" state with nothing happening to actual audio

**Comment by Adam13531** [comment]
This was fixed back in [0.2.83](https://github.com/Adam13531/BotLand/wiki/What's-new-(changelog)#client-version-0283-january-28th-2019) (but I just never closed this).
