### ISSUE TITLE
EULA/Privacy Policy Renders PDF As a cropped image

### ISSUE THREAD

**Issue by illgitthat** [Adam13531/BotLand#291]
**Steps to reproduce**
1. Go to https://play.bot.land/login
2. Click "Play As Guest"
3. Click the link for EULA and Privacy Policy
4. Left side of EULA/Privacy Policy is cropped off and appears in small box

**Expected outcome**
Maybe just link to external page?

**Browser (and version)**
Chrome Version 72.0.3626.119 (Official Build) (64-bit)

**Comment by Adam13531** [comment]
I've confirmed that this is fixed in [version 0.2.93](https://github.com/Adam13531/BotLand/wiki/What's-new-(changelog)#client-version-0293-march-2nd-2019) (live now).
