### ISSUE TITLE
The speed chosen when viewing a replay is being used in subsequent attacks

### ISSUE THREAD

**Issue by LBEVAN** [Adam13531/BotLand#30]
**Steps to reproduce**
1. View a replay
2. Change the playback speed
3. Cancel
4. Attack a player
5. Place bots and commence

**Expected outcome**
The game executes at it's normal speed (as there aren't any speed controls during attack).

**Actual outcome**
The speed chosen for the replay is used in the subsequent attacks

**Bowser information**
{"name":"Chrome","chrome":true,"version":"56.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 46
Player name: Enosis

**Comment by HiDeoo** [comment]
This is the current expected behaviour. 

More specific controls are already planned and mocked up for this and will be implemented at a later stage.
