### ISSUE TITLE
If I try to save my defense while any of my bots are dead in the test, the save fails

### ISSUE THREAD

**Issue by mpstewart** [Adam13531/BotLand#31]
**Steps to reproduce**
Place 8 bots.
Start Test
Wait for >= 1 bots to die
Click save

**Expected outcome**
I would expect the test to stop and the defense to save.

**Actual outcome**
Modal dialogue states that I must have placed 8 bots. It seems you must wait for the test to finish and the arena to reset before saving. Maybe this isn't a 'bug' but it seems really weird.

**Bowser information**
{"name":"Firefox","firefox":true,"version":"51.0","gecko":true,"linux":true,"a":true}

**In-game information**
Player ID: 3757
Player name: Demael

**Comment by Adam13531** [comment]
I addressed this by disabling saving altogether while you're testing your defense.

Commit hash: 99b56aad1dff05768a7ff088e6c18c68d692f1de
