### ISSUE TITLE
Can't scroll when viewing cosmetics and hardware in store 

### ISSUE THREAD

**Issue by riversandrew36** [Adam13531/BotLand#32]
**Steps to reproduce**
Worked well on chrome for macOS

**Expected outcome**
to be able to scroll for different items 
**Actual outcome**
can't scroll 

**Bowser information**
{"name":"Safari","safari":true,"version":"10.0","webkit":true,"mac":true,"a":true}

**In-game information**
Player ID: 108
Player name: hitchslap11

**Comment by HiDeoo** [comment]
Duplicate of #27.

**Comment by riversandrew36** [comment]
Thanks HiDeoo 👍
