### ISSUE TITLE
Too big attack button

### ISSUE THREAD

**Issue by MantasxD** [Adam13531/BotLand#35]
Attack button is too big, sorry if i writte in wrong form :D 
Image http://prntscr.com/e39gzt

**Bowser information**
{"name":"Chrome","chrome":true,"version":"55.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 3781
Player name: MantasxD

**Comment by HiDeoo** [comment]
This is now fixed with the new UI.
