### ISSUE TITLE
unsaved changes pop on exit with no changes

### ISSUE THREAD

**Issue by NPerry** [Adam13531/BotLand#4]
**Steps to reproduce**
Enter defence
Hit Save
Hit Cancel

**Expected outcome**
Main Menu
**Actual outcome**
Unsaved changes popup. 
**Bowser information**
{"name":"Chrome","chrome":true,"version":"55.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 197
Player name: nperry

**Comment by Adam13531** [comment]
This is a duplicate of #3.
