### ISSUE TITLE
Header navigation links broken on multiple page

### ISSUE THREAD

**Issue by HiDeoo** [Adam13531/BotLand#40]
**Steps to reproduce**

1. Open the Blueprint Editor
2. Try to use the **Store** / **Settings** button.

*Note: This issue can be replicated in Blockly or the code editor.*

**Expected outcome**

Go to the store or get the settings wonderful magnificent popup.

**Actual outcome**

Nothing happens.

*Note: The **Logout** button works everywhere.*

**Bowser information**

`{"name":"Chrome","chrome":true,"version":"57.0","blink":true,"mac":true,"a":true}`

**In-game information**

Player ID: 9
Player name: tempJS

**Comment by DennisRas** [comment]
This has been fixed.
Changelog: https://github.com/Adam13531/BotLand/wiki/What's-new-(changelog)#0120-march-24th-2017

Similar to #11
