### ISSUE TITLE
The window "Match Results" persists when watching a replay of your finished attack

### ISSUE THREAD

**Issue by DennisRas** [Adam13531/BotLand#44]
**Steps to reproduce**
- Start a new attack
- Win the attack (You must win or you get another bug: #45 )
- Click replay

**Expected outcome**
- Watching the replay as usual

**Actual outcome**
- The window stays 
- Clicking the "Return to main menu" doesn't send you to the main menu either - it just cancels the replay. Although this particular issue only exists because the window stays open.

![](http://i.imgur.com/WIwTPXt.png)

**Bowser information**
{"name":"Chrome","chrome":true,"version":"56.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 18
Player name: Liquidor

**Comment by HiDeoo** [comment]
This should be fixed with the new UI.

**Comment by Adam13531** [comment]
Note to self: this is only fixed because the post-match UI blocks input to the replay controls until you minimize it (which is fine).
