### ISSUE TITLE
When creating a new account, your Battle Log incorrectly says you've updated your defense

### ISSUE THREAD

**Issue by DennisRas** [Adam13531/BotLand#48]
**Steps to reproduce**
- Create a new account
- Login

**Expected outcome**
- Nothing? Haven't edited my defense yet

**Actual outcome**
- "You updated your defense 47 years ago"  
![](http://i.imgur.com/s8xjf6a.png)

**Bowser information**
{"name":"Chrome","chrome":true,"version":"56.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 5
Player name: Liquidor

**Comment by HiDeoo** [comment]
> The "last updated: 47 years ago" that you see on defenses is because I just added a "last_defense_update" column to the database and I have it set to 1970 by default.

**Comment by Adam13531** [comment]
Fixed in version 0.1.9. Commit hash: e33d2e9209898411c72bcc8c1b81b9dfd6191b80

I just stopped showing this entry in the log if you never updated your defense.
