### ISSUE TITLE
Tried setting up the Arena before Pixi was ready

### ISSUE THREAD

**Issue by HiDeoo** [Adam13531/BotLand#5]
**Steps to reproduce**

*Note: This is a random issue with no 100% repro.*

1. Go to http://play.bot.land.
2. Login.
3. Click "Edit Defense" or "Attack".

**Expected outcome**

The arena should appear with the correct mode selected (defense or attack).

**Actual outcome**

Nothing happens.

There is an error logged in the console: `Tried setting up the Arena before Pixi was ready`.

In the end, the game shouldn't be playable (aka show or have the "Edit Defense" / "Attack" buttons enabled until Pixi is really ready (maybe not even load the game at all since other parts of the website are using Pixi too. We may need a more "synchronous" way of loading things.

If this cannot easily be fixed, it could be a good idea at least in the worst case scenario to `alert()` the end user that something bad happened or even redirect him to the login page.

**Known workaround**

*Note: These workarounds do not work 100% of the time.*

* Reload the website.
* Close the tab and reopen the website in a new one.
* Quit the browser and restart it.

If none of the above workarounds work, usually waiting for a couple of minutes fix the issue.

**Bowser information**

`{"name":"Chrome","chrome":true,"version":"57.0","blink":true,"mac":true,"a":true}`

*Note: The issue can happen in all browsers.*

**In-game information**

Player ID: 267
Player name: hideo/hideo1/hideo2/hideo3/hideo4/hideo5/hideo6/hideo7

**Comment by Adam13531** [comment]
This should be fixed. I've made a lot of changes over the past couple of months that indirectly address this.
