### ISSUE TITLE
A incorrect date of "update your defense" when create a new account.

### ISSUE THREAD

**Issue by bearsoft5** [Adam13531/BotLand#50]
**Steps to reproduce**
Create a new account, and see in journal, is saying "Your updated your defense 47 years ago", should be
"You never updated your defense".

**Expected outcome**
"You never updated your defense".

**Actual outcome**
"You updated your defense 47 years ago".

**Bowser information**
{"name":"Chrome","chrome":true,"version":"56.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 22
Player name: testaekop

**Comment by HiDeoo** [comment]
Fixed in #48.
