### ISSUE TITLE
Replay doesn't work after finishing an attack

### ISSUE THREAD

**Issue by DennisRas** [Adam13531/BotLand#53]
**Steps to reproduce**
- Attack
- Finish the game
- Click the replay button
- Start the replay

**Expected outcome**
- Watch the replay

**Actual outcome**
- Replay doesn't play/begin
- The "Match Results" window stays open, but that's related to another bug #45
- Jornal or phase tracking is probably lost and getTime() is called/failing every x miliseconds

![](http://i.imgur.com/YNim4SG.png)

**Bowser information**
{"name":"Chrome","chrome":true,"version":"56.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 5
Player name: Liquidor

**Comment by DennisRas** [comment]
Did some debugging. 
Clicking a phase manually in the header will correct the error. 
Apparently there's no phase set when clicking the Replay button. 
Steps to confirm: 
- Click Replay (no phase set)
- Click a phase (1)
- Click Main Menu
- Click Replay (phase not set again)

**Comment by Adam13531** [comment]
This will be fixed beyond version 0.1.22.
