### ISSUE TITLE
Battle

### ISSUE THREAD

**Issue by selvic69** [Adam13531/BotLand#54]
**Steps to reproduce**
1. Eliminate one side of the enemy defense.
2. Attack where the first wave hit using 2nd wave. 
3. 2nd wave eliminated remaining enemies on the weak side and commence attacking the core. 
**Expected outcome**
The other enemies going towards my bots once they reach the opposite of the board. 
**Actual outcome**
The enemies just stayed there and I destroyed their core easily. 

**Bowser information**
{"name":"Chrome","chrome":true,"version":"56.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 151
Player name: selvic

**Comment by Adam13531** [comment]
I'm nearly positive this is the result of a poor defense strategy. If you don't specify a script, your bot will be given a "figureItOut();" script, which makes defenders automatically move away from the CPU by default. This isn't always desirable, but the onus is on the defender to improve their defense.
