### ISSUE TITLE
Can't exit defense replay

### ISSUE THREAD

**Issue by mlindgren** [Adam13531/BotLand#55]
**Steps to reproduce**
Watch a replay while you are defending.

**Expected outcome**
Clicking "Cancel" or "Main Menu" should take me back to the main menu.

**Actual outcome**
I'm stuck in the replay and can't return to the main menu.

**Bowser information**
{"name":"Chrome","chrome":true,"version":"56.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 147
Player name: Dag

**Comment by Adam13531** [comment]
This should be fixed after version 0.1.21; I've overhauled the replay UI.

For some history: maybe a couple of weeks ago, I pushed the unfinished replay UI inadvertently. A bunch of bugs resulted from this. I'm not sure if this particular bug is amongst that group, but it shouldn't exist any longer regardless.
