### ISSUE TITLE
NOT ENOUGH BOTCOIN TOO POOR

### ISSUE THREAD

**Issue by BeautymarkStudio** [Adam13531/BotLand#58]
**Steps to reproduce**
CLICK PLUS BUTTON TO BUY ALL TEH THINGS
**Expected outcome**
ALL TEH THINGS ARE BOUGHT
**Actual outcome**
NONE OF TEH THINGS ARE BOT I AM POOR
**Bowser information**
{"name":"Safari","safari":true,"version":"10.0","webkit":true,"mac":true,"a":true}
This bug can be replicated reliably in Chrome, Safari, Opera, Mosaic, and the thing on my phone called “Browser”. I AM PORR ON EVERY DEVICE
**In-game information**
Player ID: 141
Player name: SavageBeauty

**Comment by Adam13531** [comment]
I gave you 3000 Botcoin. Spend it wisely.
