### ISSUE TITLE
Replay speed is affecting actual gameplay

### ISSUE THREAD

**Issue by BeautymarkStudio** [Adam13531/BotLand#59]
**Steps to reproduce**
1. Play round
2. Replay
3. During replay, set playback speed to 0.5x
4. Start new round

**Expected outcome**
I would expect gameplay to be 1x, unless onscreen controls are available to manage speed myself.

**Actual outcome**
Gameplay remains at 0.5x, with no apparent way to adjust speed.

**Bowser information**
{"name":"Safari","safari":true,"version":"10.0","webkit":true,"mac":true,"a":true}

**In-game information**
Player ID: 141
Player name: SavageBeauty

**Comment by BeautymarkStudio** [comment]
Interestingly, the “% complete” counter remains visible on my screen as I play now as well — which I don't believe is the normal state of things? Anyway, it's creepy having the computer counting down (up, actually) to the my death. (I mean, usually it's my death, because I'm terrible at Bot Land.)

**Comment by HiDeoo** [comment]
Regarding the issue described in the first post, this is the current "expected" behaviour.

More specific controls are already planned and mocked up for this and will be implemented at a later stage.

**Comment by HiDeoo** [comment]
This is no longer an issue as speed controls have been added to the missing screens. All credit goes to @Skedog for pointing that out.
