### ISSUE TITLE
Shields, mines and missiles are offset

### ISSUE THREAD

**Issue by DennisRas** [Adam13531/BotLand#6]
**Steps to reproduce**
- Play a game

**Expected outcome**
- Things to be aligned

**Actual outcome**
- Shields and mines are off center (probably more)
- Missiles spawn 1 tile next to the bot
![](http://i.imgur.com/w0xYpHg.gif)

**Bowser information**
{"name":"Chrome","chrome":true,"version":"55.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 102
Player name: Liquidor

**Comment by Adam13531** [comment]
Just adding a note that right now, offsets are based on the head sprite, not the entire Pixi Container: http://imgur.com/a/gbAW6

(shown above: Scorpion Foot, Air Body, and Horse Head)

**Comment by Adam13531** [comment]
This has finally been fixed! 😄 It took forever, it made me rage-quit several streams, and I had to take an extra day off of streaming yesterday to investigate, but it's finally done.

It involved a lot of reworking of many different aspects of the rendering system.
