### ISSUE TITLE
Long usernames overlap and look awful

### ISSUE THREAD

**Issue by DennisRas** [Adam13531/BotLand#60]
I remember that the max username length was increased, so I guess this is the source of this issue.

**Steps to reproduce**
- Create or play against an account with a long username

**Expected outcome**
- Ellipsis?

**Actual outcome**
![](http://i.imgur.com/nsr7UQh.png)

**Bowser information**
{"name":"Chrome","chrome":true,"version":"56.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 5
Player name: Liquidor

**Comment by Adam13531** [comment]
I've capped both bot and user names to 15 characters (down from the 25 that the screenshot shows). This doesn't FULLY fix the problem but it greatly mitigates it.
