### ISSUE TITLE
After watching a replay you may end up editing your defense with a player attacking you

### ISSUE THREAD

**Issue by DennisRas** [Adam13531/BotLand#62]
This is very specific and probably only works becuase the Forfeit button is enabled when watching a replay, however it could be a bug with the new bottom replay bar as well. I've tested other clicks and the steps below is the only way I can reproduce this bug.

**Steps to reproduce**
- Login
- Click Replay on a Battlelog
- Click Phase 1 on the bottom navigation bar
- Click Forfeit and confirm ("Forfeit") then click "OK"
- Click the "Main menu" button

**Expected outcome**
- Going back to the main menu/home screen

**Actual outcome**
- You start editing your defense and bots from the replay gets transfered to your arena editor
- Testing/clearing doesn't work.

![](http://i.imgur.com/fvC5g2g.png)

**Bowser information**
{"name":"Chrome","chrome":true,"version":"56.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 24
Player name: Liquidor2

**Comment by Adam13531** [comment]
This should be fixed after version 0.1.21. There's no longer a Forfeit button when watching a replay.
