### ISSUE TITLE
Dropping a new chip onto a chip in the arena should swap the chips

### ISSUE THREAD

**Issue by DennisRas** [Adam13531/BotLand#63]
Just a proposal.

**Steps to reproduce**
- Edit defense
- Make sure a chip is placed in the arena
- Drag a new chip onto the chip in the arena

**Expected outcome**
- If a chip is already placed in the location that you want to drop a chip in, it should remove/swap

**Actual outcome**
- Chip that's already placed gets removed
- The chip you wanted to drop doesn't get placed

![](http://i.imgur.com/t9E1ATR.gif)

**Bowser information**
{"name":"Chrome","chrome":true,"version":"56.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 5
Player name: Liquidor

**Comment by Adam13531** [comment]
This has been finished; I just forgot to close this bug.

Proof (roughly around this timestamp): https://youtu.be/ES5ULqgO0Sw?list=PLSM9PbIe-9hWxUnzC4omVcJ-mnpHdS41F
