### ISSUE TITLE
Blockly sidebar covering navigation buttons

### ISSUE THREAD

**Issue by HiDeoo** [Adam13531/BotLand#64]
**Steps to reproduce**

1. Open the UI to create a new bot.
2. Create a new script.
3. Click on any category in the Blockly sidebar.

**Expected outcome**

Being able to still see / use the navigation buttons like `Convert to JS`, `Cancel` or `Create`.

**Actual outcome**

The buttons are covered by the Blockly sidebar.

![blockly](https://cloud.githubusercontent.com/assets/494699/24303593/de6a4aee-10b6-11e7-9e88-19edfd13d551.gif)

*Note: Another (random) issue which could be related is when right after clicking on the `Create new script` button and having the Blockly UI, sometimes the `Convert to JS` button do not react to the first click.*

*Note 2: For information, the previous day, some changes were made to Blockly in Bot Land version  0.1.20.*

**Bowser information**

{"name":"Chrome","chrome":true,"version":"59.0","blink":true,"mac":true,"a":true}

**In-game information**

Player ID: 00
Player name: incognito

**Comment by Adam13531** [comment]
I'm not completely sure *when* this was fixed, but @HiDeoo verified that this is fixed in version 0.1.69.
