### ISSUE TITLE
gameArea not defined when dragging on iPad

### ISSUE THREAD

**Issue by Adam13531** [Adam13531/BotLand#65]
**Steps to reproduce**
(too lazy to try it myself just yet, going to copy/paste from Twitch; @HiDeoo is the "real" filer!):

HiDeoo: Adam13531 Basically every mousemove event while dragging trigger that, like dragging a bot on the arena, dragging a bot already in the arena to a new position and even if the error says gameArea.offsetLeft, you even get the error while dragging a piece of hardware when editing a blueprint, same for cosmetics (so dragging & moving anything trigger that)
HiDeoo: Digging a little bit deeper, seems to be in "updateLastMouseCoordinates()"
HiDeoo: which get a pageX, pageY arguments

**Expected outcome**
No error.

**Actual outcome**
TypeError: undefined is not an object (evaluating 'gameArea.offsetLeft')

**Comment by HiDeoo** [comment]
This is no longer an issue.
