### ISSUE TITLE
Clicking Phase 1 while attacking gives a getNumPhasesRecorded error

### ISSUE THREAD

**Issue by DennisRas** [Adam13531/BotLand#66]
**Steps to reproduce**
- Login
- Click Attack
- Click Phase 1

**Expected outcome**
- Do nothing

**Actual outcome**
- Console error

![](http://i.imgur.com/5hhzca4.png)

**Bowser information**
{"name":"Chrome","chrome":true,"version":"57.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 5
Player name: Liquidor

**Comment by Adam13531** [comment]
This should be fixed after version 0.1.21.
