### ISSUE TITLE
Click Phase 1 after finishing an attack gives an AssertionError

### ISSUE THREAD

**Issue by DennisRas** [Adam13531/BotLand#67]
**Steps to reproduce**
- Login
- Attack
- Finish attack
- Click "Phase 1"

**Expected outcome**
- Same as clicking "Replay" ?

**Actual outcome**
- Nothing
- Console error
- You can't start the Replay after causing this error

![](http://i.imgur.com/ClVcnRd.png)

**Bowser information**
{"name":"Chrome","chrome":true,"version":"57.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 5
Player name: Liquidor

**Comment by Adam13531** [comment]
This is no longer a bug beyond version 0.1.21, but the expected behavior isn't totally there at the time of closing this issue (which is that you can watch a replay without the Match Results UI blocking your view).
