### ISSUE TITLE
Safari unsaved changes warning does not pop up

### ISSUE THREAD

**Issue by 3DExtended** [Adam13531/BotLand#69]
**Steps to reproduce**
Edit defense, make a script change, go back to the edit defense screen and close the tab
**Expected outcome**
A warning for unsaved changes
**Actual outcome**
No warning at all
**Bowser information**
{"name":"Safari","safari":true,"version":"10.0","webkit":true,"ipad":true,"ios":true,"osversion":"10.2.1","tablet":true,"a":true}

**In-game information**
Player ID: 115
Player name: 3dextended

**Comment by HiDeoo** [comment]
This is no longer an issue.
