### ISSUE TITLE
Can't scroll Blockly on iPad

### ISSUE THREAD

**Issue by Adam13531** [Adam13531/BotLand#70]
**Steps to reproduce**
This is actually reproducible from Chrome.

1. Press F12
2. Press ctrl+shift+M to toggle the device toolbar
3. Refresh the page so that touch handlers are installed at the beginning
4. Go to a Blockly view
5. Expand a bunch of categories (this isn't really necessary)
6. Try scrolling without using the scroll wheel

**Expected outcome**
You are able to scroll.

**Actual outcome**
It selects whichever category you started trying to scroll at.

**Bowser information**
{"name":"Chrome","chrome":true,"version":"57.0","blink":true,"android":true,"osversion":"6.0","mobile":true,"a":true}

**Other information**
This bug was found by 3DExtended on Twitch.

**Comment by Skedog** [comment]
I cannot reproduce this on my iPhone, iPad, or Chrome dev. tools - closing for now, feel free to re-open if it happens again.

**Comment by HiDeoo** [comment]
I definitely fixed this without remembering this issue, good catch.

For a bit of context, this issue in `Blockly` was due to `pixi.js` (don't ask 😟)
