### ISSUE TITLE
Can't click the buttons "Report bug" and "Packs"

### ISSUE THREAD

**Issue by DennisRas** [Adam13531/BotLand#71]
**Steps to reproduce**
- Login
- In the lobby click the "Report bug" button in the top left

**Expected outcome**
- GitHub opens
- Or the Pack Dialog opens

**Actual outcome**
- Nothing happens

The reason for this is that the new left avatar flexbox covers the buttons as shown in the screenshot below:
![](http://i.imgur.com/M0S3hSy.png)

**Bowser information**
{"name":"Chrome","chrome":true,"version":"57.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 5
Player name: Liquidor

**Comment by DennisRas** [comment]
![](http://i.imgur.com/wguOxMa.jpg)

**Comment by Adam13531** [comment]
Fixed this with the UI overhaul.
