### ISSUE TITLE
Buying a new Salvage pack gives an error

### ISSUE THREAD

**Issue by DennisRas** [Adam13531/BotLand#72]
I suppose there's an issue with some kind of currency or cooldown, because I was able to buy a salvage pack 3 times before the error appeared.

**Steps to reproduce**
- Login
- Click the "0 Packs" button top left
- Buy a salvage pack

**Expected outcome**
- You get a new salvage pack

**Actual outcome**
- An error is shown and you're left with nothing as seen in the screenshot below

![](http://i.imgur.com/7JXVbIE.png)

**Bowser information**
{"name":"Chrome","chrome":true,"version":"57.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 5
Player name: Liquidor

**Comment by HiDeoo** [comment]
This might have been fixed as I can no longer repro, feel free to re-open if you hit it again.
