### ISSUE TITLE
When attempting to login in as soon as form loads....

### ISSUE THREAD

**Issue by CalebBabin** [Adam13531/BotLand#73]
**Steps to reproduce**
Save your botland login credentials in your browsers password manager and go to play.bot.land while it's online, press enter as soon as you see the form filled in by autofill to attempt to log in by hitting enter or clicking the button really fast.

**Expected outcome**
you log in

**Actual outcome**
an alert pops up saying invalid username or password

you might be able to throttle your network connection to help reproduce this result, waiting for the page to fully load does not result in this bug.

**Bowser information**
{"name":"Chrome","chrome":true,"version":"58.0","blink":true,"windows":true,"a":true,"this info came from adams browser because report bug button is broken":true}

**Comment by HiDeoo** [comment]
This is no longer happening to me in either Chrome or Safari. I'm closing this for now, feel free to re-open if this is still an issue.
