### ISSUE TITLE
TypeError: oldBlueprints is null

### ISSUE THREAD

**Issue by HiDeoo** [Adam13531/BotLand#75]
**Steps to reproduce**

1. Use Firefox
2. Login
3. Refresh (cmd + R)

**Expected outcome**

No error

**Actual outcome**

Getting a console error 

`TypeError: oldBlueprints is null`

**Bowser information**

`{"name":"Firefox","firefox":true,"version":"51.0","gecko":true,"mac":true,"a":true}`

**In-game information**

Player ID: 13
Player name: incognito

**Comment by HiDeoo** [comment]
This seems to be fixed as I can no longer reproduce the issue.

**Comment by Adam13531** [comment]
I can't hunt down the exact change this was in, but I did fix this a while ago without realizing there was a corresponding issue here on GitHub.
