### ISSUE TITLE
Testing a defense with a chip selected does not unselect the chip.

### ISSUE THREAD

**Issue by HiDeoo** [Adam13531/BotLand#77]
**Steps to reproduce**

1. Edit your defense.
2. Expand the chip panel
3. Select a chip.
4. Test your defense.

**Expected outcome**

When going into defense with a chip selected, the chip should be unselected and the chip preview following the cursor should be removed. This is the behavior for bots.

![repro](http://i.imgur.com/ALPNaIg.gif)

**Actual outcome**

The selected chip is not unselected and the preview is still attached to the cursor.

_Additional informations:_

* This also prevent clicking on a bot when testing your defense and be able to place on a tile. You have to drag it around.

**Bowser information**

{"name":"Chrome","chrome":true,"version":"60.0","blink":true,"mac":true,"a":true}

**In-game information**

Player ID: 13
Player name: incognito

**Comment by HiDeoo** [comment]
This seems to be fixed with the new testing UI.

**Comment by Adam13531** [comment]
I think this was something I specifically fixed without realizing there was a corresponding issue here on GitHub.
