### ISSUE TITLE
Wrong bot is removed if selecting another bot of the same type/id

### ISSUE THREAD

**Issue by DennisRas** [Adam13531/BotLand#79]
**Steps to reproduce**
- Login
- Edit Defense
- Select a bot in the arena
- Select another bot of the same type/blueprint
- Click "Remove bot"

**Expected outcome**
- The currently selected bot is removed

**Actual outcome**
- The previously selected bot gets removed

![](http://i.imgur.com/nTGVogB.gif)

**Bowser information**
{"name":"Chrome","chrome":true,"version":"58.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 5
Player name: Liquidor

**Comment by Adam13531** [comment]
I think this is the same bug as #61 which is still present in the game. It's correct that this particular manifestation of the bug is no long present.
