### ISSUE TITLE
Shader: UV - Coords are wrong

### ISSUE THREAD

**Issue by 3DExtended** [Adam13531/BotLand#8]
**Steps to reproduce**

take this shader:

[Shader on BPaste](https://bpaste.net/show/c1bd2608e111)

and than scroll. 

**Expected outcome**

You should NOT see a difference of the color, since the UV Coord should be always a value between 0 and 1.

**Actual outcome**

But you see it changing on scrolling.

**Browser (and version)**

Firefox 

**Operating system (and version)**

Win 10

**Comment by 3DExtended** [comment]
Also you can see that the UV coords are changing depending, when the bot is not fully visible

**Comment by Adam13531** [comment]
Thanks a million for filing this bug!

It's "fixed" by exposing mapCoord in the shader, so any calculations other than texture2D that __would__ have used vTextureCoord should now use mapCoord.

Commit hash: ebbefb1fb287ee1a3dc72225606f89901eaa0dee
Version available: 0.1.20+
