### ISSUE TITLE
Animation flickering in the arena

### ISSUE THREAD

**Issue by DennisRas** [Adam13531/BotLand#80]
**Steps to reproduce**
- Have bots touch and overlap eachother in the arena

**Expected outcome**
- Smooth criminal

**Actual outcome**
![](http://i.imgur.com/UBhiJo5.gif)

**Bowser information**
{"name":"Chrome","chrome":true,"version":"58.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 5
Player name: Liquidor

**Comment by Adam13531** [comment]
Fixed. Turns out the sort I was using was unstable on some browsers (e.g. Chrome), so I added a property to make the sorting deterministic.

Commit hash: 47b1ffcbcc99f3ffb7efe1f22daeb2f9bd1d6996
Fix available after version: 0.1.44
