### ISSUE TITLE
You can remove your own bots during replay after an attack 

### ISSUE THREAD

**Issue by DennisRas** [Adam13531/BotLand#81]
**Steps to reproduce**
- Attack someone
- Win or Lose
- Click Phase 1
- Click one of your bots and remove it

**Expected outcome**
- Shouldn't be able to remove or edit the bot

**Actual outcome**
- Bot gets edited/removed and the replay crashes
- You can click the phase again to reset the replay

![](http://i.imgur.com/BJROllU.png)

**Bowser information**
{"name":"Chrome","chrome":true,"version":"58.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 5
Player name: Liquidor

**Comment by HiDeoo** [comment]
This seems to be fixed as this button no longer exist in the new UI.
