### ISSUE TITLE
Bot hardware covering 'X' in arena

### ISSUE THREAD

**Issue by Skedog** [Adam13531/BotLand#83]
**Steps to reproduce**

1. Go to arena
2. Click on bot
3. Click on top hardware item

**Expected outcome**
Red highlight shouldn't cover the "x" to close the dialog. The red highlight class has a z-index:5 being applied to it, which is causing the x to show below it.

**Actual outcome**
Red highlight covers the "x"

**Bowser information**
{"name":"Chrome","chrome":true,"version":"59.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 21
Player name: skedog

https://gyazo.com/acb5c20e67de66c85f91398cb2d2d38a

**Comment by Adam13531** [comment]
Fixed. Commit hash: 792f038c437c7cd6f532e3c4564ab1c276658316

Should be present after version 0.1.44.
