### ISSUE TITLE
There is a single replay speed for all modes

### ISSUE THREAD

**Issue by RokuHF** [Adam13531/BotLand#84]
**Steps to reproduce**
go to test defense
max speed out
go to attack another player
speed will remain maxed out

**Expected outcome**
ultra high-speed against other player gameplay

**Actual outcome**

**Bowser information**
{"name":"Chrome","chrome":true,"version":"60.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 1741
Player name: notgay

**Comment by HiDeoo** [comment]
Similar issue as #59, this is the current "expected" behaviour.

More specific controls are already planned and mocked up for this and will be implemented at a later stage.

**Comment by Adam13531** [comment]
While replay speeds are still global to all modes, they're now reset to 1x each time you enter an attack or edit your defense. I'm closing this since there are no plans to change this behavior in the near future, but I do want to keep an eye on feedback like this.
