### ISSUE TITLE
Script editor pane makes Prettify/Create buttons disappear

### ISSUE THREAD

**Issue by shrmpy** [Adam13531/BotLand#85]
**Steps to reproduce**
From home screen, click Edit-Defense button. Choose bot on left column. Choose angle brackets (<>) to edit script. Choose down/expand and plus (+) to get into New Script mode. From the script editor pane, paste script text that is more than 23 lines (my test input is saved at [jsfiddle.net/13oedwfg/](http://jsfiddle.net/13oedwfg/)). Notice as you remove lines back down to 20, the Prettify/Create buttons re-appear.

**Expected outcome**
Prettify/Create buttons float above editor pane and stay available.

**Actual outcome**
Prettify/Create buttons disappear below as the editor pane grows past 23rd line of script text.

**Bowser information**
{"name":"Safari","safari":true,"version":"10.1","webkit":true,"mac":true,"a":true}
I experienced this behavior in both Safari and Firefox (attached ff screen capture)
![editscript](https://user-images.githubusercontent.com/24621188/29802570-f7676dac-8c2a-11e7-8f6e-c590a09376eb.png)
.

**In-game information**
Player ID: 1672
Player name: shrmpy

**Comment by Adam13531** [comment]
I'm not completely sure *when* this was fixed, but @HiDeoo verified that this is fixed in version 0.1.69.
