### ISSUE TITLE
Can't click buttons after test defense glitch

### ISSUE THREAD

**Issue by renji7** [Adam13531/BotLand#86]
**Steps to reproduce**
Had just finished testing a defense. Went to go test the defense again.

**Expected outcome**
For defense to get tested.

**Actual outcome**
It started making weird noises and an orb graphic/blob thing showed up in the top corner of the map.  I could still click the speed change buttons though. Then I got it to stop but then clicking "test" or "test defense" did nothing. Couldn't click "clear all" either. See attached video. [Bot Land - Google Chrome 9_3_2017 12_27_25 AM.zip](https://github.com/Adam13531/BotLand/files/1272786/Bot.Land.-.Google.Chrome.9_3_2017.12_27_25.AM.zip)

**Browser (and version)**
Version 60.0.3112.113 (Official Build) (64-bit)

**Operating system (and version)**
Windows 10 Pro Version 1607 OS Build 14393.1593

**In-game information**
Player ID: 1777
Player name: renji7

**Comment by Adam13531** [comment]
@renji7, thanks for filing this. Unfortunately, I don't have enough information to be able to discern what happened here, so I'm going to have to close this.

If you ever hit this again, please press F12 to open DevTools and copy/paste the errors that show up in the console. Ideally that step wouldn't be necessary and I'd have something auto-upload the logs to an error-collection server, but I don't have that set up yet. :(
