### ISSUE TITLE
Placing a bot sometimes does not work and you have to click many times

### ISSUE THREAD

**Issue by NFLWeb** [Adam13531/BotLand#9]
**Steps to reproduce**
Attempt to place a bot and it seems to take a couple click before registering.
**Expected outcome**
No bot is placed on the first click and you have to click 3 or 4 more times.
**Actual outcome**
No bot is place and you have to click a couple more times before it happens.
**Bowser information**
{"name":"Chrome","chrome":true,"version":"55.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 8
Player name: NoobForLunch

**Comment by DennisRas** [comment]
Theory/Issue: The time between mousedown and mouseup is too slow thereby making the click not count as an actual click. This makes the placement not trigger. The issue has something to do with the mouse/pointer event handlers.

@NFLWeb could you try and click slowly (down then up) and see if that doesn't work and then try again with a fast click?

**Comment by HiDeoo** [comment]
The issue mostly comes from the behavior of Hammer.js and its current configuration.

Tweaking these values can indeed reduce / minimize this bug but add other bugs. This configuration has been a long on-going issue unfortunately.

**Comment by Adam13531** [comment]
If you still see this problem after January 2017, then please reopen this issue. As of version 0.1.2, the press threshold should be increased from 100ms to 200ms. If people still complain about taps not being recognized as taps, then I may have to fix this some other way. If people instead complain about presses taking too long, then I can try lowering this value a little bit, but 100ms is clearly unacceptable.
