### ISSUE TITLE
EULA attempts to give you the possibility to sue people if you deem whatever they do 'to be against the spirit or intent of the Services'

### ISSUE THREAD

**Issue by JonasT** [Adam13531/BotLand#90]
The EULA says:

> You acknowledge you will not directly or indirectly. Partake in any activity or action that XTONOMOUS deems to be against the spirit or intent of the Services.

It also says:

> You and XTONOMOUS acknowledge that breach of this agreement may result in irreparable harm and loss, and upon a breach of this agreement the non-breaching party (i.e. you and/or XTONOMOUS) shall be entitled to immediate injunctive relief from a court of competent jurisdiction, which is in addition to, not in lieu of remedies at law and/or any other remedies set forth in this agreement.

This basically seems to imply you can sue people for damages in whatever way you like if they do something you personally deem not in the "spirit or intent of the Services", which has to be the most vague nonsense license clause of the century.

Needless to say, I suggest this is changed unless you hate your players.

PS: I'm not a lawyer, but I sometimes read terms of use.

**Comment by JonasT** [comment]
I think the real problem is the ridiculous statement that "you ... acknowledge that breach of this agreement may result in irreparable harm and loss, and upona breach of this agreement the non-breaching party (i.e. you and/or XTONOMOUS) shall be entitled to immediate injunctive relief".

I have never seen anything like this before.

I just checked another terms of use for comparison, and what the *reasonable* terms put in is to state that if you cause them harm they will be entitled to damages, or if you cause harm to third-parties with resulting claims to damages against them you will pay for those. **None of them** says something silly like "oh and WHATEVER you possibly do which is part of ANYTHING in these entire terms of use can possibly be considered to cause damages" - for obvious reasons.

PS: I'm not a lawyer, but I sometimes read terms of use.

**Comment by Adam13531** [comment]
See comments to #89 for why I'm closing this.
