### ISSUE TITLE
Incomplete EULA (missing mail)

### ISSUE THREAD

**Issue by HiDeoo** [Adam13531/BotLand#92]
**Steps to reproduce**

Visit the EULA

**Expected outcome**

Have the full EULA

**Actual outcome**

Incomplete EULA

![https://i.imgur.com/SyG73aV.png](https://i.imgur.com/SyG73aV.png)

**Browser (and version)**

Netscape

**Operating system (and version)**

Casio Calculator OS

**Comment by Adam13531** [comment]
(note: still an issue as of 5/1/18)

**Comment by Adam13531** [comment]
> Browser (and version)
> Netscape
> Operating system (and version)
> Casio Calculator OS

HAR HAR, @HiDeoo.

I've finally fixed this. I also updated both the EULA and the PP.
