### ISSUE TITLE
Code editor has a white background white

### ISSUE THREAD

**Issue by HiDeoo** [Adam13531/BotLand#93]
**Steps to reproduce**

Go the code editor.

**Expected outcome**

Not becoming blind.

**Actual outcome**

Becoming blind.

![Eyes](http://i.imgur.com/MlI5NtG.gif)

**Browser (and version)**

All browsers from Netscape to links.

**Operating system (and version)**

All OSes

**Comment by W1lkins** [comment]
Tkahns for tihs bug ropert.

Hvae jsut treid to cfionrm it melysf - can cnrofim - am now bilnd

**Comment by Pnoexz** [comment]
While you are at it, can you make the code editor autofocus when you enter the page?

**Comment by Adam13531** [comment]
Finally fixed this. Now you can start complaining about how Blockly still has a white background.

Commit hash: 88a63936204340d9b04076bc04820802e12edf67
Fix will be present after version 0.2.21
