### ISSUE TITLE
An empty table (currently used for weapon stats) displays under the cosmetics/chips descriptions

### ISSUE THREAD

**Issue by judgebacon** [Adam13531/BotLand#98]
**Steps to reproduce**
1. Open the store
2. Click on a cosmetic or chip
3. Look under the description of said cosmetic or chip

**Expected outcome**
No table to show for cosmetics/chips, or for it to only populate/show if there's information to show

**Actual outcome**
The empty table shows under the cosmetics and chips descriptions:

![image](https://user-images.githubusercontent.com/32315725/31034161-c43be68a-a55a-11e7-89e8-e36e882a7e9c.png)
![image](https://user-images.githubusercontent.com/32315725/31034144-a8097400-a55a-11e7-8fe4-ff05746a899a.png)

**Bowser information**
{"name":"Chrome","chrome":true,"version":"61.0","blink":true,"mac":true,"a":true}

**In-game information**
Player ID: 1274
Player name: JudgeBacon

**Comment by Adam13531** [comment]
This is an incredibly good catch! I don't know how you manage to see this stuff. :P

Fixed. Commit hash: 4d3c83b7ac7797bdfff8aa265040570ff3f02237. Fix will be present after version 0.1.74.
