### ISSUE TITLE
Adding x number of (level 1) types of hardware on a bot causes hardware to overflow off the page/over other elements

### ISSUE THREAD

**Issue by judgebacon** [Adam13531/BotLand#99]
**Steps to reproduce**
1. Edit/configure a bots hardware
2. Add x number of level 1 types of hardware to said bot until you see the hardware overlap other elements and/or run off the page.

Note: the number of hardware types you add for it to overflow may vary, in my case more than 5 types.

**Expected outcome**
The hardware to not overlap other elements/run off the page. Perhaps sticking the hardware in a scrollable element would fix this (scrollbar only visible when the hardware begins to overflow).

**Actual outcome**
![image](https://user-images.githubusercontent.com/32315725/31100776-afeb8dec-a7c2-11e7-8e2b-9be0f601b3e4.png)

**Bowser information**
{"name":"Chrome","chrome":true,"version":"61.0","blink":true,"mac":true,"a":true}

**In-game information**
Player ID: 1274
Player name: JudgeBacon

**Extra info**
Screen resolution: 2560 x 1600

**Comment by Adam13531** [comment]
I don't recall exactly when, but I added short descriptions for items, so while this can still happen, it looks much better as long as the browser is at least ~800px tall:

![image](https://user-images.githubusercontent.com/7192897/31979068-9a747f6c-b8f9-11e7-9981-db5f8bc8fcc8.png)
